# SPDX-License-Identifier: GPL-2.0-or-later
# Algebroids: Algebroids and bialgebroids as preadditive categories generated by enhanced quivers
#
# Implementations
#

SetInfoLevel( InfoAlgebroids, 1 );

@InstallValueConst( ALGEBROIDS,
        @rec(
            ring = HomalgFieldOfRationals( ),
           )
);

####################################
#
# methods for attributes:
#
####################################

##
@InstallMethod( Range,
        "for a primitive path",
        [ IsPrimitivePath && IsNontrivialPath && IsArrow ],
        
  Target );

##
@InstallMethod( Dimension,
        "for an algebroid",
        [ IsAlgebroid ],
        
  function( A )
    local kq;
    
    kq = UnderlyingQuiverAlgebra( A );
    
    if (@not IsFiniteDimensional( kq ))
        return infinity;
    end;
    
    return Dimension( kq );
    
end );

##
@InstallMethod( AssignSetOfObjects,
        [ IsAlgebroid, IsString ],
        
  function( A, label )
    local names, objects, func;
    
    names = List( Vertices( UnderlyingQuiver( A ) ), StringGAP );
    
    objects = SetOfObjects( A );
    
    func = function( name, o )
              
              if (IntGAP( name ) != fail && label == "")
                  Error( "The second argument should be a non-empty string" );
              end;
              
              name = @Concatenation( label, ReplacedString( name, "-", "m" ) );
              
              MakeReadWriteGlobal( name );
              
              @BindGlobal( name, o );
              
              return 1;
              
            end;
            
    ListN( names, objects, func );
    
end );

##
@InstallMethod( AssignSetOfObjects,
        [ IsAlgebroid && HasUnderlyingQuiver ],
        
  function( A )
  
    AssignSetOfObjects( A, "" );
    
end );

##
InstallMethodWithCache( SetOfGeneratingMorphisms,
        "for an algebroid and two objects",
        [ IsAlgebroid && HasUnderlyingQuiver, IsObjectInAlgebroid, IsObjectInAlgebroid ],
        
  ( A, obj_1, obj_2 ) -> Filtered( SetOfGeneratingMorphisms( A ), m -> IsEqualForObjects( obj_1, Source( m ) ) && IsEqualForObjects( obj_2, Target( m ) ) )
);

##
@InstallMethod( SetOfGeneratingMorphisms,
        "for two objects in an algebroid",
         [ IsObjectInAlgebroid, IsObjectInAlgebroid ],
         
  ( obj_1, obj_2 ) -> SetOfGeneratingMorphisms( CapCategory( obj_1 ), obj_1, obj_2 )
);

##
InstallMethodWithCache( SetOfGeneratingMorphisms,
        "for an algebroid and two integers",
        [ IsAlgebroid && HasUnderlyingQuiver, IsInt, IsInt ],
        
  ( A, i, j ) -> SetOfGeneratingMorphisms( A, SetOfObjects( A )[ i ], SetOfObjects( A )[ j ] )
);

##
@InstallMethod( AssignSetOfGeneratingMorphisms,
        [ IsAlgebroid, IsString ],
        
  function( A, label )
    local names, morphisms, func;
    
    names = List( Arrows( UnderlyingQuiver( A ) ), StringGAP );
    
    morphisms = SetOfGeneratingMorphisms( A );
    
    func = function( name, m )
              
              if (IntGAP( name ) != fail && label == "")
                  Error( "The second argument should be a non-empty string" );
              end;
              
              name = @Concatenation( label, ReplacedString( name, "-", "m" ) );
              
              MakeReadWriteGlobal( name );
              
              @BindGlobal( name, m );
              
              return 1;
              
            end;
            
    ListN( names, morphisms, func );
    
end );

##
@InstallMethod( AssignSetOfGeneratingMorphisms,
        [ IsAlgebroid && HasUnderlyingQuiver ],
        
  function( A )
    
    AssignSetOfGeneratingMorphisms( A, "" );
    
end );


##
@InstallMethod( RelationsOfAlgebroid,
        "for an algebroid",
        [ IsAlgebroid && HasUnderlyingQuiverAlgebra ],
        
  function( A )
    local relations;
    
    relations = RelationsOfAlgebra( UnderlyingQuiverAlgebra( A ) );
    
    relations = Filtered( relations, r -> @not IsZero( r ) );
    
    return List( relations, a -> MorphismInAlgebroid( A, a ) );
    
end );

##
@InstallMethod( BijectionBetweenPairsAndElementaryTensors,
        "for a QPA quiver algebra",
        [ IsQuiverAlgebra ],
        
  function( Qq )
    local Qqq, gens, prod;
    
    if (HasPathAlgebra( Qq ))
        Qq = PathAlgebra( Qq );
    end;
    
    Qqq = TensorProductOfAlgebras( Qq, Qq );
    
    gens = PrimitivePaths( QuiverOfAlgebra( Qq ) );
    
    gens = Cartesian( gens, gens );
    
    prod = List( gens,
                  p -> ElementaryTensor(
                          PathAsAlgebraElement( Qq, p[1] ),
                          PathAsAlgebraElement( Qq, p[2] ),
                          Qqq ) );
    
    
    prod = List( prod, a -> Paths( Representative( a ) )[1] );
    
    return [ prod, gens ];
    
end );

##
@InstallMethod( DecompositionOfMorphismInAlgebroid,
        "for a morphism in an algebroid",
        [ IsMorphismInAlgebroid ],
        
  function( mor )
    local B, func;
    
    B = CapCategory( mor );
    
    mor = UnderlyingQuiverAlgebraElement( mor );
    
    mor = DecomposeQuiverAlgebraElement( mor );
    
    func =
      function( a )
        return List( a,
                     function( f )
                       f = B[StringGAP( f ]);
                       if (IsCapCategoryObject( f ))
                           return IdentityMorphism( f );
                       end;
                       return f;
                     end );
        
      end;
    
    mor[2] = List( mor[2], func );
    
    return ListN( mor[1], mor[2], function( r, s ) return [ r, s ]; end );
    
end );

##
@InstallMethod( DecompositionOfMorphismInSquareOfAlgebroid,
        "for a morphism in an algebroid",
        [ IsMorphismInAlgebroid ],
        
  function( mor )
    local B, Rq, gens, prod, func;
    
    B = CapCategory( mor ).PowerOf;
    
    Rq = UnderlyingQuiverAlgebra( B );
    
    gens = BijectionBetweenPairsAndElementaryTensors( Rq );
    prod = gens[2];
    gens = gens[1];
    
    mor = UnderlyingQuiverAlgebraElement( mor );
    
    mor = DecomposeQuiverAlgebraElement( mor );
    
    mor[2] = List( mor[2], p -> List( p, a -> prod[Position( gens, a )] ) );
    
    func =
      function( a )
        return List( a,
                     function( f )
                       f = B[StringGAP( f ]);
                       if (IsCapCategoryObject( f ))
                           return IdentityMorphism( f );
                       end;
                       return f;
                     end );
        
      end;
    
    mor[2] = List( mor[2], p -> List( p, func ) );
    
    return ListN( mor[1], mor[2], function( r, s ) return [ r, s ]; end );
    
end );

##
@InstallMethod( AssociatedAlgebroid,
        "for a linear closure of a path category",
        [ IsLinearClosure ],
        
  function( lin_closure_of_path_cat )
    local P;
    
    P = UnderlyingCategory( lin_closure_of_path_cat );
    
    if (@not IsPathCategory( P ))
        TryNextMethod( );
    end;

    if (HasRangeCategoryOfHomomorphismStructure( lin_closure_of_path_cat ))
        return Algebroid( AssociatedFreeCategory( P ), RangeCategoryOfHomomorphismStructure( lin_closure_of_path_cat ) );
    else
        return Algebroid( CommutativeRingOfLinearCategory( lin_closure_of_path_cat ), AssociatedFreeCategory( P ) );
    end;
    
end );

##
@InstallMethod( AssociatedAlgebroid,
        "for a quotient of a linear closure of a path category",
        [ IsQuotientCategory ],
        
  function( quot_of_lin_closure_of_path_cat )
    local L, A, objs, mors, rels, func;
    
    L = AmbientCategory( quot_of_lin_closure_of_path_cat );
    
    if (@not IsLinearClosure( L ))
        TryNextMethod( );
    end;
    
    A = AssociatedAlgebroid( L );
    
    objs = SetOfObjects( A );
    mors = SetOfGeneratingMorphisms( A );
    
    rels = DefiningRelations( quot_of_lin_closure_of_path_cat );
    
    func =
      function( lin_comb )
        local coef, supp, n, source, target;
        
        coef = CoefficientsList( lin_comb );
        supp = SupportMorphisms( lin_comb );
        
        n = Length( supp );
        @Assert( 0, n == Length( coef ) );
        
        source = objs[ObjectIndex( ObjectDatum( Source( lin_comb ) ) )];
        target = objs[ObjectIndex( ObjectDatum( Target( lin_comb ) ) )];
        
        return LinearCombinationOfMorphisms( A,
                       source,
                       coef,
                       List( supp, mor ->
                             PreComposeList( A,
                                     source,
                                     mors[MorphismIndices( mor )],
                                     target ) ),
                       target );
        
    end;
    
    if (HasRangeCategoryOfHomomorphismStructure( quot_of_lin_closure_of_path_cat ))
        return QuotientCategory( A, List( rels, func )
                      ; range_of_HomStructure = RangeCategoryOfHomomorphismStructure( quot_of_lin_closure_of_path_cat ) );
    else
        return A / List( rels, func );
    end;
    
end );

####################################
#
# methods for operation:
#
####################################

##
@InstallMethod( DecomposeQuiverAlgebraElement,
        "for a quiver algebra element",
        [ IsQuiverAlgebraElement ],
        
  function( p )
    
    if (IsQuotientOfPathAlgebraElement( p ))
        p = Representative( p );
    end;
    
    return [ Coefficients( p ),
             List( Paths( p ),
                   function( a )
                     if (Length( a ) == 0)
                         return [ a ];
                     end;
                     return ArrowList( a );
                   end ) ];
    
end );

##
@InstallMethod( ApplyToQuiverAlgebraElement,
        "for an object function, a morphism function, a category, a quiver algebra element and a boolean",
        [ IsFunction, IsFunction, IsCapCategory, IsQuiverAlgebraElement, IsBool ],
        
  function( object_func, morphism_func, range_category, p, covariant )
    local applyF, paths, paths_final;
    
    # function to be applied to an arrow (or a vertex representing the trivial path at this vertex)
    applyF =
      function( b )
        local m;
        
        if (IsQuiverVertex( b ))
            m = object_func( b );
            return IdentityMorphism( m );
        end;
        
        return morphism_func( b );
        
    end;
    
    paths = DecomposeQuiverAlgebraElement( p )[2];
    
    if (covariant)
        paths_final = List( paths, a -> PreCompose( List( a, applyF ) ) );
    else
        paths_final = List( paths, a -> PreCompose( Reversed( List( a, applyF ) ) ) );
    end;
    
    return PreCompose( paths_final );
    
end );

##
@InstallMethod( ApplyToQuiverAlgebraElement,
        "for an object function, a morphism function, a linear category, a quiver algebra element, and a boolean",
        [ IsFunction, IsFunction, IsCapCategory && IsLinearCategoryOverCommutativeRing, IsQuiverAlgebraElement, IsBool ],
        
  function( object_func, morphism_func, range_category, p, covariant )
    local applyF, paths, coefs, paths_final, s, all_objects_in_image;

    if (IsZero( p ))
        Error( "cannot handle the zero path algebra element, as it contains no information about its source and target\n" );
    end;
    
    # function to be applied to an arrow (or a vertex representing the trivial path at this vertex)
    applyF =
      function( b )
        local m;
        
        if (IsQuiverVertex( b ))
            m = object_func( b );
            return IdentityMorphism( m );
        end;
        
        return morphism_func( b );
        
    end;
      
    paths = DecomposeQuiverAlgebraElement( p );
    
    coefs = paths[1];
    paths = paths[2];

    if (covariant)
        paths_final = List( paths, a -> PreCompose( List( a, applyF ) ) );
    else
        paths_final = List( paths, a -> PreCompose( Reversed( List( a, applyF ) ) ) );
    end;
    
    if (Length( coefs ) > 0)
        s = Sum( ListN( coefs, paths_final, function( r, p ) return r * p; end ) );
    end;
    
    return s;
    
end );

##
@InstallMethod( ApplyToQuiverAlgebraElement,
        "for a functor and a quiver algebra element",
        [ IsCapFunctor, IsQuiverAlgebraElement ],

  function( functor, p )
    local algebroid, func;
    
    algebroid = AsCapCategory( Source( functor ) );
    
    func = b -> ApplyFunctor( functor, algebroid[StringGAP( b ]) );
    
    if (@IsBound( functor.IsContravariant ) && functor.IsContravariant)
        return ApplyToQuiverAlgebraElement( func, func, AsCapCategory(Target(functor)), p, false );
    end;
    
    return ApplyToQuiverAlgebraElement( func, func, AsCapCategory(Target(functor)), p, true );
    
end );

####################################
#
# methods for constructors:
#
####################################

##
@InstallGlobalFunction( ADD_FUNCTIONS_FOR_ALGEBROID,
  
  function( category, over_Z )
    
    ##
    AddObjectConstructor( category,
      function( category, v )
        
        return ObjectInAlgebroid( category, v );
        
    end );
    
    ##
    AddObjectDatum( category,
      function( category, o )
        
        return UnderlyingVertex( o );
        
    end );
    
    ##
    AddMorphismConstructor( category,
      function( category, source, m, range )
        
        return MorphismInAlgebroid( category, source, m, range );
        
    end );
    
    ##
    AddMorphismDatum( category,
      function( category, m )
        
        return UnderlyingQuiverAlgebraElement( m );
        
    end );
    
    ##
    AddSetOfObjectsOfCategory( category,
      function( category )
        
        return List( Vertices( UnderlyingQuiver( category ) ), o -> category[StringGAP( o] ) );
        
    end );
    
    ##
    AddSetOfGeneratingMorphismsOfCategory( category,
      function( category )
        
        return List( Arrows( UnderlyingQuiver( category ) ), o -> category[StringGAP( o ] ) );
        
    end );
    
    ##
    AddIsWellDefinedForObjects( category,
      function( category, o )
        local v;
        
        v = UnderlyingVertex( o );
        
        return IsQuiverVertex( v ) && QuiverOfPath( v ) == UnderlyingQuiver( category );
        
    end );
    
    ##
    AddIsWellDefinedForMorphisms( category,
      function( category, alpha )
        local m;
        
        m = UnderlyingQuiverAlgebraElement( alpha );
        
        if (@not AlgebraOfElement( m ) == UnderlyingQuiverAlgebra( category ))
            
            return false;
            
        elseif (IsZero( m ))
            
            return true;
            
        elseif (@not ForAll( Paths( m ), p -> UnderlyingVertex( Source( alpha ) ) == Source( p ) ))
            
            return false;
            
        elseif (@not ForAll( Paths( m ), p -> UnderlyingVertex( Target( alpha ) ) == Target( p ) ))
            
            return false;
            
        end;
        
        # all tests passed, so it is well-defined
        return true;
        
    end );
    
    ##
    AddIsEqualForObjects( category,
      function( category, object_1, object_2 )
        
        return UnderlyingVertex( object_1 ) == UnderlyingVertex( object_2 );
        
    end );
    
    ##
    AddIsEqualForMorphisms( category,
      function( category, morphism_1, morphism_2 )
        
        return UnderlyingQuiverAlgebraElement( morphism_1 ) == UnderlyingQuiverAlgebraElement( morphism_2 );
        
    end );
    
    ##
    AddIsCongruentForMorphisms( category,
      function( category, morphism_1, morphism_2 )
        
        return UnderlyingQuiverAlgebraElement( morphism_1 ) == UnderlyingQuiverAlgebraElement( morphism_2 );
        
    end );
    
    ##
    AddIdentityMorphism( category,
      function( category, object )
        local quiver_algebra, id;
        
        quiver_algebra = UnderlyingQuiverAlgebra( category );
        
        id = PathAsAlgebraElement( quiver_algebra, QuiverVertexAsIdentityPath( UnderlyingVertex( object ) ) );
        
        return MorphismInAlgebroid( category,
                       object,
                       id,
                       object );
        
    end );
    
    if (IsRightQuiver( UnderlyingQuiver( category ) ))
        
        ##
        AddPreCompose( category,
          function( category, morphism_1, morphism_2 )
            
            return MorphismInAlgebroid( category,
                           Source( morphism_1 ),
                           UnderlyingQuiverAlgebraElement( morphism_1 ) * UnderlyingQuiverAlgebraElement( morphism_2 ),
                           Target( morphism_2 ) );
            
        end );
        
    else
        
        ##
        AddPreCompose( category,
          function( category, morphism_1, morphism_2 )
            
            return MorphismInAlgebroid( category,
                           Source( morphism_1 ),
                           UnderlyingQuiverAlgebraElement( morphism_2 ) * UnderlyingQuiverAlgebraElement( morphism_1 ),
                           Target( morphism_2 ) );
            
        end );
        
    end;
    
    ##
    AddAdditionForMorphisms( category,
      function( category, morphism_1, morphism_2 )
        
        return MorphismInAlgebroid( category,
                       Source( morphism_1 ),
                       UnderlyingQuiverAlgebraElement( morphism_1 ) + UnderlyingQuiverAlgebraElement( morphism_2 ),
                       Target( morphism_1 ) );
        
    end );
    
    ##
    AddAdditiveInverseForMorphisms( category,
      function( category, morphism )
        
        return MorphismInAlgebroid( category,
                       Source( morphism ),
                       -UnderlyingQuiverAlgebraElement( morphism ),
                       Target( morphism ) );
        
    end );
    
    ##
    AddMultiplyWithElementOfCommutativeRingForMorphisms( category,
      function( category, r, morphism )
        
        return MorphismInAlgebroid( category,
                       Source( morphism ),
                       r * UnderlyingQuiverAlgebraElement( morphism ),
                       Target( morphism ) );
        
    end );
    
    ##
    AddZeroMorphism( category,
      function( category, S, T )
        
        return MorphismInAlgebroid( category,
                       S,
                       Zero( UnderlyingQuiverAlgebra( category ) ),
                       T );
        
    end );
    
    AddIsZeroForMorphisms( category,
      function( category, morphism )
        
        return IsZero( UnderlyingQuiverAlgebraElement( morphism ) );
        
    end );
    
    ## only create the Hom-structure for finite dimensional quiver algebras
    if (IsFiniteDimensional( UnderlyingQuiverAlgebra( category ) ))
        
        ADD_FUNCTIONS_FOR_HOM_STRUCTURE_OF_ALGEBROID( category, over_Z );
        
        ADD_FUNCTIONS_FOR_RANDOM_METHODS_OF_ALGEBROID( category, over_Z );
        
    end;
    
    Finalize( category );
    
    SetFilterObj( IdentityFunctor( category ), IsAlgebroidMorphism );
    
    return category;
    
end );

##
@InstallMethod( SetOfObjects,
        "for an algebroid",
        [ IsAlgebroid ],
        
  function( cat )
    
    return SetOfObjectsAsUnresolvableAttribute( cat );
    
end );

##
@InstallMethod( SetOfGeneratingMorphisms,
        "for an algebroid",
        [ IsAlgebroid ],
        
  function( cat )
    
    return SetOfGeneratingMorphismsAsUnresolvableAttribute( cat );
    
end );

##
@InstallGlobalFunction( ADD_FUNCTIONS_FOR_HOM_STRUCTURE_OF_ALGEBROID,
  function( algebroid, over_Z )
    local quiver_algebra, quiver, vertices, basis, basis_paths_by_vertex_index,
          basis_morphisms_by_vertex_index, path,
          MATRIX_FOR_HOMSTRUCTURE, hom_structure_on_basis_paths,
          ring, default_range_of_HomStructure, range_category;
    
    quiver_algebra = UnderlyingQuiverAlgebra( algebroid );
    
    ## Prepare quick access to basis elements
    quiver = QuiverOfAlgebra( quiver_algebra );
    
    vertices = Vertices( quiver );
    
    basis = BasisPaths( CanonicalBasis( quiver_algebra ) );
    
    ## prepare the homomorphism structure
    
    ## storing the basis paths
    ## basis_paths_by_vertex_index[ v_index ][ w_index ] == [ p_1:v -> w, p_2:v -> w, ... ]
    
    basis_paths_by_vertex_index = List( vertices, i -> List( vertices, i -> [ ] ) );
    
    basis_morphisms_by_vertex_index = List( vertices, i -> List( vertices, i -> [ ] ) );
    
    for path in basis
        
        Add( basis_paths_by_vertex_index[ VertexIndex( Source( path ) ) ][ VertexIndex( Target( path ) ) ], path );
        
        Add( basis_morphisms_by_vertex_index[ VertexIndex( Source( path ) ) ][ VertexIndex( Target( path ) ) ], MorphismInAlgebroid( algebroid, PathAsAlgebraElement( quiver_algebra, path ) ) );
        
    end;
    
    # if `basis_paths_by_vertex_index` would be mutable, setting the attribute below would create an (immuatable) copy,
    # which would not be identical to `basis_paths_by_vertex_index` anymore
    MakeImmutable( basis_paths_by_vertex_index );
    
    SetBasisPathsByVertexIndex( algebroid, basis_paths_by_vertex_index );
    
    @Assert( 0, IsIdenticalObj( basis_paths_by_vertex_index, BasisPathsByVertexIndex( algebroid ) ) );
    
    MakeImmutable( basis_morphisms_by_vertex_index );
    
    SetBasisMorphismsByVertexIndex( algebroid, basis_morphisms_by_vertex_index );
    
    @Assert( 0, IsIdenticalObj( basis_morphisms_by_vertex_index, BasisMorphismsByVertexIndex( algebroid ) ) );
    
    ## precomputing matrices for the hom structure
    ## hom_structure_on_basis_paths[ v_index ][ w_index ][ v'_index ][ w'_index ][ basis_path_1_index ][ basis_path_2_index ] =
    ## [ Hom(v,w) -> Hom(v',w'): x -> basis_path_1 * x * basis_path_2 ]
    ## for basis_path_1: v' -> v and basis_path_2: w -> w'
    
    MATRIX_FOR_HOMSTRUCTURE = function( v, w, vp, wp, path_1, path_2 )
        local mat, hom_v_w, hom_vp_wp, alpha, beta, path;
        
        mat = [];
        
        hom_v_w = basis_paths_by_vertex_index[ VertexIndex( v ) ][ VertexIndex( w ) ];
        
        if (IsEmpty( hom_v_w ))
            
            return mat;
            
        end;
        
        hom_vp_wp = basis_paths_by_vertex_index[ VertexIndex( vp ) ][ VertexIndex( wp ) ];
        
        if (IsEmpty( hom_vp_wp ))
            
            return mat;
            
        end;
        
        alpha = PathAsAlgebraElement( quiver_algebra, path_1 );
        
        beta = PathAsAlgebraElement( quiver_algebra, path_2 );
        
        for path in hom_v_w
            
            Add( mat,
                 CoefficientsOfPaths( hom_vp_wp, alpha * PathAsAlgebraElement( quiver_algebra, path ) * beta )
                 );
            
        end;
        
        return mat;
        
    end;
    
    hom_structure_on_basis_paths =
        List( vertices, v ->
            List( vertices, w ->
                List( vertices, vp ->
                    List( vertices, wp ->
                        List( basis_paths_by_vertex_index[ VertexIndex( vp ) ][ VertexIndex( v ) ], basis_path_1 ->
                            List( basis_paths_by_vertex_index[ VertexIndex( w ) ][ VertexIndex( wp ) ], basis_path_2 ->
                                MATRIX_FOR_HOMSTRUCTURE( v, w, vp, wp, basis_path_1, basis_path_2 )
                            )
                        )
                    )
                )
            )
        );
    
    # if `hom_structure_on_basis_paths` would be mutable, setting the attribute below would create an (immuatable) copy, which would not be identical to `hom_structure_on_basis_paths` anymore
    MakeImmutable( hom_structure_on_basis_paths );
    
    SetHomStructureOnBasisPaths( algebroid, hom_structure_on_basis_paths );
    
    @Assert( 0, IsIdenticalObj( hom_structure_on_basis_paths, HomStructureOnBasisPaths( algebroid ) ) );
    
    ring = CommutativeRingOfLinearCategory( algebroid );
    
    if (ValueOption( "no_precompiled_code" ) == true)
        
        default_range_of_HomStructure = CategoryOfRows_as_AdditiveClosure_RingAsCategory( ring );
        
    else
        
        default_range_of_HomStructure = CategoryOfRows( ring );
        
    end;
    
    range_category = CAP_INTERNAL_RETURN_OPTION_OR_DEFAULT( "range_of_HomStructure", default_range_of_HomStructure );
    
    if (!(IsCategoryOfRows( range_category ) || (IsBoundGlobal( "IsMatrixCategory" ) && ValueGlobal( "IsMatrixCategory" )( range_category ))))
        
        Error( "range_of_HomStructure must be a category of rows or a matrix category" );
        
    end;
    
    SET_RANGE_CATEGORY_Of_HOMOMORPHISM_STRUCTURE( algebroid, range_category );
    
    ##
    AddHomomorphismStructureOnObjects( algebroid,
      function( algebroid, object_1, object_2 )
        local nr_source, nr_range, basis_elements;
        
        nr_source = VertexIndex( UnderlyingVertex( object_1 ) );
        
        nr_range = VertexIndex( UnderlyingVertex( object_2 ) );
        
        basis_elements = BasisPathsByVertexIndex( algebroid )[nr_source][nr_range];
        
        return ObjectConstructor( range_category, Length( basis_elements ) );
        
    end );
    
    ##
    AddHomomorphismStructureOnMorphismsWithGivenObjects( algebroid,
      function( algebroid, source, alpha, beta, range )
        local elem_alpha, elem_beta, a, b, ap, bp, basis_paths_by_vertex_index,
              basis_ap_a, basis_b_bp, size_source, size_range, coeffs_alpha, coeffs_beta, entries;
        
        elem_alpha = UnderlyingQuiverAlgebraElement( alpha );
        
        elem_beta = UnderlyingQuiverAlgebraElement( beta );
        
        a = VertexIndex( UnderlyingVertex( Target( alpha ) ) );
        
        b = VertexIndex( UnderlyingVertex( Source( beta ) ) );
        
        ap = VertexIndex( UnderlyingVertex( Source( alpha ) ) );
        
        bp = VertexIndex( UnderlyingVertex( Target( beta ) ) );
        
        basis_paths_by_vertex_index = BasisPathsByVertexIndex( algebroid );
        
        basis_ap_a = basis_paths_by_vertex_index[ap][a];
        
        basis_b_bp = basis_paths_by_vertex_index[b][bp];
        
        # getting the sizes from `source` and `range` is more efficient for the compiler
        size_source = ObjectDatum( range_category, source );
        size_range = ObjectDatum( range_category, range );
        
        # the brackets allow the compiler to hoist the condition `IsZeroForMorphisms( algebroid, alpha ) or size_source == 0` more easily
        if ((IsZeroForMorphisms( algebroid, alpha ) || size_source == 0) || (IsZeroForMorphisms( algebroid, beta ) || size_range == 0))
            
            return ZeroMorphism( range_category, source, range );
            
        else
            
            ## These two lines need QPA in a dynamic way
            coeffs_alpha = CoefficientsOfPaths( basis_ap_a, elem_alpha );
            coeffs_beta = CoefficientsOfPaths( basis_b_bp, elem_beta );
            
            # If Length( basis_ap_a ) == 0 (resp. Length( basis_b_bp ) == 0), then alpha (resp. beta) must be zero,
            # and these cases are handled above -> we can ignore the empty cases here.
            entries = Sum(
                (1):(Length( basis_ap_a )),
                p ->
                Sum(
                    (1):(Length( basis_b_bp )),
                    q -> coeffs_alpha[p] * coeffs_beta[q] * HomStructureOnBasisPaths( algebroid )[ a ][ b ][ ap ][ bp ][ p ][ q ]
                )
            );
            
            return MorphismConstructor( range_category, source, HomalgMatrixListList( entries, size_source, size_range, ring ), range );
            
        end;
        
    end );
    
    ##
    AddDistinguishedObjectOfHomomorphismStructure( algebroid,
      function( algebroid )
        
        return ObjectConstructor( range_category, 1 );
        
    end );
    
    ##
    AddInterpretMorphismAsMorphismFromDistinguishedObjectToHomomorphismStructure( algebroid,
      function( algebroid, alpha )
        local a, b, basis_elements, size_basis, source, range, element;
        
        a = VertexIndex( UnderlyingVertex( Source( alpha ) ) );
        
        b = VertexIndex( UnderlyingVertex( Target( alpha ) ) );
        
        basis_elements = BasisPathsByVertexIndex( algebroid )[a][b];
        
        size_basis = Length( basis_elements );
        
        source = DistinguishedObjectOfHomomorphismStructure( algebroid );
        range = HomomorphismStructureOnObjects( algebroid, Source( alpha ), Target( alpha ) );
        
        if (size_basis == 0)
            
            return ZeroMorphism( range_category, source, range );
            
        end;
        
        element = UnderlyingQuiverAlgebraElement( alpha );
        
        return MorphismConstructor(
                range_category,
                source,
                HomalgMatrixListList( [ CoefficientsOfPaths( basis_elements, element ) ], 1, size_basis, ring ),
                range
              );
        
    end );
    
    ##
    AddInterpretMorphismFromDistinguishedObjectToHomomorphismStructureAsMorphism( algebroid,
      function( algebroid, a, b, morphism )
        local coefficients, basis, element;
        
        coefficients = EntriesOfHomalgMatrixAsListList( MorphismDatum( range_category, morphism ) )[1];
        
        basis = BasisPathsByVertexIndex( algebroid )[VertexIndex( UnderlyingVertex( a ) )][VertexIndex( UnderlyingVertex( b ) )];
        
        element = QuiverAlgebraElement( quiver_algebra, coefficients, basis );
        
        return MorphismInAlgebroid( algebroid, a, element, b );
        
    end );
    
    ## Both methods can be derived, but it is more efficient to add them as primitive methods.
    
    SetIsLinearCategoryOverCommutativeRingWithFinitelyGeneratedFreeExternalHoms( algebroid, true );
    
    ##
    AddBasisOfExternalHom( algebroid,
      function( algebroid, object_1, object_2 )
        local a, b;
        
        a = VertexIndex( UnderlyingVertex( object_1 ) );
        
        b = VertexIndex( UnderlyingVertex( object_2 ) );
        
        return BasisMorphismsByVertexIndex( algebroid )[a][b];
        
    end );
    
    ##
    AddCoefficientsOfMorphism( algebroid,
      function( algebroid, alpha )
        local a, b, element;
        
        a = VertexIndex( UnderlyingVertex( Source( alpha ) ) );
        
        b = VertexIndex( UnderlyingVertex( Target( alpha ) ) );
        
        element = UnderlyingQuiverAlgebraElement( alpha );
        
        return CoefficientsOfPaths( BasisPathsByVertexIndex( algebroid )[a][b], element );
        
    end );
    
end );

##
@InstallGlobalFunction( ADD_FUNCTIONS_FOR_RANDOM_METHODS_OF_ALGEBROID,
  function( A, over_Z )
    
    if (over_Z)
      
      # to
      return;
      
    else
      
      AddRandomObjectByInteger( A,
        ( A, n ) -> Random( SetOfObjects( A ) )
      );
      
      AddRandomMorphismWithFixedSourceByInteger( A,
        function( A, o, n )
          local objects, p, b;
          
          objects = Shuffle( ShallowCopy( SetOfObjects( A ) ) );
          
          p = PositionProperty( objects, obj -> @not IsZero( HomStructure( o, obj ) ) );
          
          if (p == fail)
              return Random( (0):(AbsInt( n )) ) * One( UnderlyingAlgebra( A ) ) * IdentityMorphism( o );
          end;
          
          b = BasisOfExternalHom( o, objects[ p ] );
          
          return Sum( List( (0):(AbsInt( n )), i -> Random( b ) ) );
          
      end );
      
      AddRandomMorphismWithFixedRangeByInteger( A,
        function( A, o, n )
          local objects, p, b;
          
          objects = Shuffle( ShallowCopy( SetOfObjects( A ) ) );
          
          p = PositionProperty( objects, obj -> @not IsZero( HomStructure( obj, o ) ) );
          
          if (p == fail)
              return Random( (0):(AbsInt( n )) ) * One( UnderlyingAlgebra( A ) ) * IdentityMorphism( o );
          end;
          
          b = BasisOfExternalHom( objects[ p ], o );
          
          return Sum( List( (0):(AbsInt( n )), i -> Random( b ) ) );
          
      end );
      
      AddRandomMorphismWithFixedSourceAndRangeByInteger( A,
        function( A, s, r, n )
          local b;
          
          b = BasisOfExternalHom( s, r );
          
          if (IsEmpty( b ))
              return ZeroMorphism( s, r );
          end;
          
          return Sum( List( (0):(AbsInt( n )), i -> Random( b ) ) );
          
      end );
      
    end;
    
end );

@BindGlobal( "ADD_FUNCTIONS_FOR_AdditiveClosureOfAlgebroidPrecompiled", function ( cat )
  local A, Rq, is_finite_dimensional, is_right_quiver, over_field;
    
    @Assert( 0, IsAdditiveClosureCategory( cat ) );
    
    A = UnderlyingCategory( cat );
    
    @Assert( 0, IsAlgebroid( A ) );
    
    Rq = UnderlyingQuiverAlgebra( A );
    
    is_finite_dimensional = IsFiniteDimensional( Rq );
    
    is_right_quiver = IsRightQuiver( QuiverOfAlgebra( Rq ) );
    
    over_field = @not A.over_Z;
    
    if (is_finite_dimensional && is_right_quiver && over_field && IsCategoryOfRows( RangeCategoryOfHomomorphismStructure( A ) ))
        
        ADD_FUNCTIONS_FOR_AdditiveClosureOfAlgebroidOfFiniteDimensionalQuiverAlgebraOfRightQuiverOverFieldPrecompiled( cat );
        
        return true;
        
    elseif (is_finite_dimensional && is_right_quiver && @not over_field && IsCategoryOfRows( RangeCategoryOfHomomorphismStructure( A ) ))
        
        ADD_FUNCTIONS_FOR_AdditiveClosureOfAlgebroidOfFiniteDimensionalQuiverAlgebraOfRightQuiverOverZPrecompiled( cat );
        
        return true;
        
    else
        
        return false;
        
    end;
    
end );

@BindGlobal( "ADD_FUNCTIONS_FOR_AdelmanCategoryOfAdditiveClosureOfAlgebroidPrecompiled", function ( cat )
  local Add, A, Rq, is_finite_dimensional, is_right_quiver, over_field;
    
    @Assert( 0, IsAdelmanCategory( cat ) );
    
    Add = UnderlyingCategory( cat );
    
    @Assert( 0, IsAdditiveClosureCategory( Add ) );
    
    A = UnderlyingCategory( Add );
    
    @Assert( 0, IsAlgebroid( A ) );
    
    Rq = UnderlyingQuiverAlgebra( A );
    
    is_finite_dimensional = IsFiniteDimensional( Rq );
    
    is_right_quiver = IsRightQuiver( QuiverOfAlgebra( Rq ) );
    
    over_field = @not A.over_Z;
    
    if (is_finite_dimensional && is_right_quiver && over_field && IsCategoryOfRows( RangeCategoryOfHomomorphismStructure( A ) ))
        
        ADD_FUNCTIONS_FOR_AdelmanCategoryOfAdditiveClosureOfAlgebroidOfFiniteDimensionalQuiverAlgebraOfRightQuiverOverFieldPrecompiled( cat );
        
        return true;
        
    elseif (is_finite_dimensional && is_right_quiver && @not over_field && IsCategoryOfRows( RangeCategoryOfHomomorphismStructure( A ) ))
        
        ADD_FUNCTIONS_FOR_AdelmanCategoryOfAdditiveClosureOfAlgebroidOfFiniteDimensionalQuiverAlgebraOfRightQuiverOverZPrecompiled( cat );
        
        return true;
        
    else
        
        return false;
        
    end;
    
end );

##
@InstallMethod( Algebroid,
        "for a QPA quiver algebra and a boolean",
        [ IsQuiverAlgebra, IsBool ],
        
  function( Rq, over_Z )
    local domain, paths, p, q, parity, quiver, A;
    
    domain = LeftActingDomain( Rq );
    
    if (over_Z)
        
        if (IsIdenticalObj( domain, Rationals )
           ||
           ( HasIsRationalsForHomalg( domain ) && IsRationalsForHomalg( domain )
             && @not IsHomalgExternalRingRep( domain ) )
       )
            
            ## Test if the multiplication table which is induced by the basis of the quiver algebra
            ## (computed by the Groebner basis) only has integral coefficients.
            paths = BasisPaths( CanonicalBasis( Rq ) );
            
            for p in paths
                
                for q in paths
                    
                    if (@not ForAll( Coefficients( PathAsAlgebraElement( Rq, p ) * PathAsAlgebraElement( Rq, q ) ), IsInt ))
                        
                        Error( "the basis of the given quiver algebra does give rise to a well-defined algebroid over Z\n");
                        
                    end;
                    
                end;
                
            end;
            
        else
            
            Error( "the left acting domain of the given quiver algebra is not supported for constructing an algebroid of the integers\n");
            
        end;
        
    end;
    
    if (IsRightQuiverAlgebra( Rq ))
        parity = "Right";
    else
        parity = "Left";
    end;
    
    quiver = QuiverOfAlgebra( Rq );

    if (Length( Vertices( quiver ) ) > 1)
        A = "Algebroid( ";
    else
        A = "Algebra( ";
    end;
    
    if (over_Z)
        A = @Concatenation( A, "Z, " );
    else
        A = @Concatenation( A, RingName( domain ), ", " );
    end;
    
    A = @Concatenation( A, "FreeCategory( ", parity, "Quiver( \"", StringGAP( quiver ), "\" ) ) )" );
    
    if (@not IsPathAlgebra( Rq ))
        A = @Concatenation( A, " / relations" );
    end;
    
    A = CreateCapCategoryWithDataTypes( A,
                 IsAlgebroid,
                 IsObjectInAlgebroid,
                 IsMorphismInAlgebroid,
                 IsCapCategoryTwoCell,
                 IsQuiverVertex,
                 IsQuiverAlgebraElement,
                 fail );
    
    SetDefiningTripleOfUnderlyingQuiver( A, DefiningTripleOfAQuiver( quiver ) );
    
    A.compiler_hints =
      @rec( category_attribute_names =
           [ "SetOfObjectsAsUnresolvableAttribute",
             "SetOfGeneratingMorphismsAsUnresolvableAttribute",
             "UnderlyingQuiver",
             "UnderlyingQuiverAlgebra",
             "BasisPathsByVertexIndex",
             "BasisMorphismsByVertexIndex",
             "HomStructureOnBasisPaths",
             "DefiningTripleOfUnderlyingQuiver",
             ],
           precompiled_towers = [
            @rec(
                remaining_constructors_in_tower = [ "AdditiveClosure" ],
                precompiled_functions_adder = ADD_FUNCTIONS_FOR_AdditiveClosureOfAlgebroidPrecompiled
            ),
            @rec(
                remaining_constructors_in_tower = [ "AdditiveClosure", "AdelmanCategory" ],
                precompiled_functions_adder = ADD_FUNCTIONS_FOR_AdelmanCategoryOfAdditiveClosureOfAlgebroidPrecompiled
            ),
        ],
    );
    
    DeactivateCachingOfCategory( A );
    CapCategorySwitchLogicOff( A );
    DisableSanityChecks( A );
    
    SetIsAbCategory( A, true );
    SetIsLinearCategoryOverCommutativeRing( A, true );
    
    SetIsFinitelyPresentedLinearCategory( A, true );
    SetUnderlyingQuiver( A, quiver );
    SetUnderlyingAlgebra( A, domain );
    SetParity( A, parity );
    
    if (over_Z)
        SetCommutativeRingOfLinearCategory( A, HomalgRingOfIntegers() );
    else
        SetCommutativeRingOfLinearCategory( A, LeftActingDomain( Rq ) );
    end;
    A.over_Z = over_Z;
    
    SetUnderlyingQuiverAlgebra( A, Rq );
    if (Length( Vertices( quiver ) ) == 1)
        SetFilterObj( A, IsAlgebraAsCategory );
    end;
    
    A.Vertices = @rec( );
    A.Arrows = @rec( );
    
    return ADD_FUNCTIONS_FOR_ALGEBROID( A, over_Z );
    
end );

##
@InstallMethod( Algebroid,
        "for a QPA quiver algebra",
        [ IsQuiverAlgebra ],
        
  function( A )
    
    return Algebroid( A, false );
    
end );

##
@InstallMethod( Algebroid,
        "for a QPA path algebra, a list, and a boolean",
        [ IsQuiverAlgebra, IsList, IsBool ],
        
  function( Rq, L, over_Z )
    local path;
    
    for path in L
        if (@not IsUniform( path ))
            Error( "only uniform relations are admissible, while the path algebra element ", path, " is not uniform\n" );
        end;
    end;
    
    L = Filtered( L, r -> @not IsZero( r ) );
    
    return Algebroid( Rq / Ideal( Rq, L ), over_Z );
    
end );

##
@InstallMethod( Algebroid,
        "for a QPA path algebra and a list",
        [ IsQuiverAlgebra, IsList ],
        
  function( Rq, L )
    
    return Algebroid( Rq, L, false );
    
end );

##
@InstallMethod( Algebroid,
        "for a homalg ring and a QPA quiver",
        [ IsHomalgRing, IsQuiver ],
        
  function( R, quiver )
    local A;
    
    A = PathAlgebra( R, quiver );
    
    SetRingFilter( A, IsQuiverAlgebra );
    SetRingElementFilter( A, IsQuiverAlgebraElement );
    
    return Algebroid( A );
    
end );

##
InstallMethodWithCache( Algebroid,
        "for a homalg ring and a finitely presented category",
        [ IsHomalgRing, IsFpCategory ],
        
  function( k, C )
    local relations, kq, A, over_Z;
    
    relations = C.relations;
    
    if (relations == [ ] && @not IsPathAlgebra( UnderlyingQuiverAlgebra( C ) ))
        Error( "the underlying quiver algebra is not a path algebra, nevertheless the list of relations is empty\n" );
    end;
    
    if (HasIsIntegersForHomalg( k ) && IsIntegersForHomalg( k ))
        k = HomalgFieldOfRationals( );
        over_Z = true;
    else
        over_Z = false;
    end;
    
    kq = PathAlgebra( k, UnderlyingQuiver( C ) );
    
    SetRingFilter( kq, IsQuiverAlgebra );
    SetRingElementFilter( kq, IsQuiverAlgebraElement );
    
    relations = List( relations, a -> PathAsAlgebraElement( kq, a[1] ) - PathAsAlgebraElement( kq, a[2] ) );
    
    A = kq / Ideal( kq, relations );
    
    A = kq / GroebnerBasis( IdealOfQuotient( A ) );
    
    SetRingFilter( A, IsQuiverAlgebra );
    SetRingElementFilter( A, IsQuiverAlgebraElement );
    
    A = Algebroid( A, over_Z ); ## do @not call the single argument method Algebroid as it is an attribute
    
    SetUnderlyingCategory( A, C );
    
    SetIsLinearClosureOfACategory( A, true );
    
    return A;
    
end );

##
InstallMethodWithCache( Algebroid,
        "for a finitely presented category and a category",
        [ IsFpCategory, IsCapCategory ],
        
  function( C, H )
    local relations, k, kq, A, over_Z;
    
    relations = C.relations;
    
    if (relations == [ ] && @not IsPathAlgebra( UnderlyingQuiverAlgebra( C ) ))
        Error( "the underlying quiver algebra is not a path algebra, nevertheless the list of relations is empty\n" );
    end;
    
    k = CommutativeRingOfLinearCategory( H );
    
    if (HasIsIntegersForHomalg( k ) && IsIntegersForHomalg( k ))
        k = HomalgFieldOfRationals( );
        over_Z = true;
    else
        over_Z = false;
    end;
    
    kq = PathAlgebra( k, UnderlyingQuiver( C ) );
    
    relations = List( relations, a -> PathAsAlgebraElement( kq, a[1] ) - PathAsAlgebraElement( kq, a[2] ) );
    
    A = kq / Ideal( kq, relations );
    
    A = kq / GroebnerBasis( IdealOfQuotient( A ) );
    
    A = Algebroid( A, over_Z; range_of_HomStructure = H ); ## do @not call the single argument method Algebroid as it is an attribute
    
    SetUnderlyingCategory( A, C );
    
    SetIsLinearClosureOfACategory( A, true );
    
    return A;
    
end );

##
@InstallMethod( getindex,
        "for a homalg ring and a finitely presented category",
        [ IsHomalgRing, IsFpCategory ],
        
  Algebroid );

##
@InstallMethod( QuotientCategory,
        "for an algebroid and a list",
        [ IsAlgebroid, IsList ],

  function( A, relations )
    
    return Algebroid( UnderlyingQuiverAlgebra( A ), List( relations, UnderlyingQuiverAlgebraElement ), A.over_Z );
    
end );

##
@InstallMethod( /,
        "for an algebroid and a list",
        [ IsAlgebroid, IsList ],

  function( A, relations )
    
    return QuotientCategory( A, relations );
    
end );

##
@InstallMethod( DescentToZDefinedByBasisPaths,
        "for an algebroid",
        [ IsAlgebroid ],
        
  function( A )
    
    return Algebroid( UnderlyingQuiverAlgebra( A ), true );
    
end );

##
@InstallMethod( Multiplication,
        "for a commutative algebra as cateogry",
        [ IsAlgebraAsCategory && IsCommutative ],
        
  function( A )
    local unique_object_in_A, unique_object_in_A_string,
          morphisms_in_A, A2, unique_object_in_A2, unique_object_in_A2_string,
          mult_functor_images_of_objects, mult_functor_images_of_generating_morphisms,
          a, b, axg, axg_string, fxb, fxb_string, mult_functor, g, f;

    unique_object_in_A = SetOfObjects( A )[1];
    unique_object_in_A_string = StringGAP( UnderlyingVertex( unique_object_in_A ) );
    morphisms_in_A = SetOfGeneratingMorphisms(A);

    A2 = A*A;
    
    unique_object_in_A2 = SetOfObjects( A2 )[1];
    unique_object_in_A2_string = StringGAP( UnderlyingVertex( unique_object_in_A2 ) );
    
    mult_functor_images_of_objects = @rec( );
    mult_functor_images_of_objects[unique_object_in_A2_string] = unique_object_in_A;

    mult_functor_images_of_generating_morphisms = @rec(); # FIXME

    a = unique_object_in_A;
    b = unique_object_in_A;

    for g in morphisms_in_A

        axg = ElementaryTensor( a, g, A2 );
        axg_string = StringGAP( LeadingPath( Representative( UnderlyingQuiverAlgebraElement( axg ) ) ) );

        mult_functor_images_of_generating_morphisms[axg_string] = g;

    end;

    for f in morphisms_in_A

        fxb = ElementaryTensor( f, b, A2 );
        fxb_string = StringGAP( LeadingPath( Representative( UnderlyingQuiverAlgebraElement( fxb ) ) ) );

        mult_functor_images_of_generating_morphisms[fxb_string] = f;

    end;
    
    mult_functor = CapFunctor( A2, mult_functor_images_of_objects, mult_functor_images_of_generating_morphisms );
    
    return mult_functor;

end );

##
@InstallMethod( Unit,
        "for algebra as category",
        [ IsAlgebraAsCategory ],
        
  function( A )
    local unique_object_in_A, unique_object_in_A_string,
          unique_object_in_A0, unique_object_in_A0_string,
          unit_functor_images_of_objects, unit_functor_images_of_generating_morphisms, A0;
    
    unique_object_in_A = SetOfObjects( A )[1];
    unique_object_in_A_string = StringGAP( UnderlyingVertex( unique_object_in_A ) );
    
    A0 = A^0;
    
    unique_object_in_A0 = SetOfObjects( A0 )[1];
    unique_object_in_A0_string = StringGAP( UnderlyingVertex( unique_object_in_A0 ) );
    
    unit_functor_images_of_objects = @rec( );
    unit_functor_images_of_objects[unique_object_in_A0_string] = unique_object_in_A;
    unit_functor_images_of_generating_morphisms = @rec( );
    
    return CapFunctor(A0, unit_functor_images_of_objects, unit_functor_images_of_generating_morphisms );
end );

##
@InstallMethod( ObjectInAlgebroid,
         "for an algebroid and a vertex of a quiver",
        [ IsAlgebroid, IsQuiverVertex ],
        
  function( A, v )
    local name, obj;
    
    name = StringGAP( v );
    
    obj = CreateCapCategoryObjectWithAttributes( A,
                   UnderlyingVertex, v,
                   Label, name );
    
    #% CAP_JIT_DROP_NEXT_STATEMENT
    A.Vertices[name] = obj;
    
    return obj;
    
end );

##
@InstallMethod( MorphismInAlgebroid,
        "for an algebroid, two objects in this algebroid and an element of the quiver algebra",
        [ IsAlgebroid, IsObjectInAlgebroid, IsQuiverAlgebraElement, IsObjectInAlgebroid ],
        
  function( A, S, path, T )
    local l;
    
    #% CAP_JIT_DROP_NEXT_STATEMENT
    if (@not IsZero( path ))
        
        if (@not IsUniform( path ))
            Error( "the quiver algebra element ", path, " is neither zero nor uniform\n" );
        end;
        
        ## TODO: we are avoiding for the moment the sanity test for
        ## elements of path algebras with relations, this should be
        ## reintroduced in the future
        if (IsPathAlgebraElement( path ))
            l = LeadingPath( path );
        
            if (!( Source( l ) == UnderlyingVertex( S ) ) && !( Target( l ) == UnderlyingVertex( T ) ))
                Error( "the path algebra element ", path, " is not zero, it does not match the given source S and it does not match the given target T\n" );
            elseif (!( Source( l ) == UnderlyingVertex( S ) ))
                Error( "the path algebra element ", path, " is not zero and it does not match the given source S\n" );
            elseif (!( Target( l ) == UnderlyingVertex( T ) ))
                Error( "the path algebra element ", path, " is not zero and it does not match the given target T\n" );
            end;
        end;
        
    end;
    
    #% CAP_JIT_DROP_NEXT_STATEMENT
    CAP_INTERNAL_ASSERT_IS_OBJECT_OF_CATEGORY( S, A, () -> "the source given to MorphismInAlgebroid" );
    
    #% CAP_JIT_DROP_NEXT_STATEMENT
    CAP_INTERNAL_ASSERT_IS_OBJECT_OF_CATEGORY( T, A, () -> "the range given to MorphismInAlgebroid" );
    
    return CreateCapCategoryMorphismWithAttributes( A,
                   S,
                   T,
                   UnderlyingQuiverAlgebraElement, path );
    
end );

##
@InstallMethod( MorphismInAlgebroid,
               "for two objects in an algebroid and an element of the quiver algebra",
               [ IsObjectInAlgebroid, IsQuiverAlgebraElement, IsObjectInAlgebroid ],
               
  function( S, path, T )
    
    return MorphismInAlgebroid( CapCategory( S ), S, path, T );
    
end );

##
@InstallMethod( \.,
        "for an algebroid and a positive integer",
        [ IsAlgebroid, IsPosInt ],
        
  function( B, string_as_int )
    local name, q, a, b;
    
    name = NameRNam( string_as_int );
    
    q = UnderlyingQuiver( B );
    
    a = q[name];
    
    if (IsQuiverVertex( a ))
        if (@IsBound( B.Vertices[name] ))
            return B.Vertices[name];
        end;
        b = ObjectInAlgebroid( B, a );
    elseif (IsArrow( a ) || IsCompositePath( a ))
        if (@IsBound( B.Arrows[name] ))
            return B.Arrows[name];
        end;
        b = MorphismInAlgebroid(
                     B[StringGAP( Source( a ] ) ),
                     PathAsAlgebraElement( UnderlyingQuiverAlgebra( B ), a ),
                     B[StringGAP( Target( a ] ) ) );
        SetLabel( b, name );
        B.Arrows[name] = b;
    else
        Error( "the given component ", name, " is neither a vertex nor an arrow of the quiver q == ", q, "\n" );
    end;
    
    return b;
    
end );

##
@InstallMethod( MorphismInAlgebroid,
        "for an algebroid and an element of a path algebra",
        [ IsAlgebroid, IsPathAlgebraElement ],
        
  function( A, path )
    local l, S, T;
    
    if (IsZero( path ))
        Error( "source and target of the zero path is ambiguous\n" );
    elseif (@not IsUniform( path ))
        Error( "the path algebra element ", path, " is not uniform\n" );
    end;
    
    l = LeadingPath( path );
    
    S = StringGAP( Source( l ) );
    T = StringGAP( Target( l ) );
    
    return MorphismInAlgebroid( A, A[S], path, A[T] );
    
end );

##
@InstallMethod( /,
        [ IsPathAlgebraElement, IsAlgebroid ],
        
  function( path, A )
    
    return MorphismInAlgebroid( A, path );
    
end );

##
@InstallMethod( MorphismInAlgebroid,
        "for an algebroid and an element of a quotient of a path algebra",
        [ IsAlgebroid, IsQuotientOfPathAlgebraElement ],
        
  function( A, path )
    local l, S, T;
    
    if (IsZero( path ))
        Error( "source and target of the zero path is ambiguous\n" );
    elseif (@not IsUniform( path ))
        Error( "the quiver algebra element ", path, " is not uniform\n" );
    end;
    
    l = LeadingPath( Representative( path ) );
    
    S = StringGAP( Source( l ) );
    T = StringGAP( Target( l ) );
    
    return MorphismInAlgebroid( A, A[S], path, A[T] );
    
end );

##
@InstallMethod( /,
        [ IsQuotientOfPathAlgebraElement, IsAlgebroid ],
        
  function( path, A )
    
    return MorphismInAlgebroid( A, path );
    
end );

##
@InstallMethod( ^,
        "for an algebroid and an integer",
        [ IsAlgebroid && HasUnderlyingQuiverAlgebra, IsInt ],
        
  function( A, n )
    local Rq, R, parity;
    
    if (n < 0)
        Error( "the only admissible values for n are non-negative integers\n" );
    elseif (n == 1)
        return A;
    elseif (@not @IsBound( A.powers ))
        A.powers = @rec( );
    end;
    
    Rq = UnderlyingQuiverAlgebra( A );
    
    R = LeftActingDomain( Rq );
    
    if (n == 0)
        
        if (@not @IsBound( A.powers.0 ))
            
            if (IsRightQuiverAlgebra( Rq ))
                parity = "Right";
            else
                parity = "Left";
            end;
            
            A.powers.0 = TrivialAlgebroid( R, parity );
            
        end;
        
        return A.powers.0;
        
    end;
    
    A.powers.1 = A;
    
    if (@not @IsBound( A.powers[n] ))
        if (@not @IsBound( A.powers[n-1] ))
            A.powers[n-1] = A^(n-1);
        end;
        
        A.powers[n] = A.powers[n-1] * A;
        
        A.powers[n].PowerOf = A;
        
    end;
    
    return A.powers[n];
    
end );

##
@InstallMethod( TrivialAlgebroid,
        "for a homalg ring and a string",
        [ IsHomalgRing, IsString ],
        
  function( R, parity )
    local trivial_quiver;
    
    if (parity == "Right")
        trivial_quiver = RightQuiver( "*(1)[]" );
    elseif (parity == "Left")
        trivial_quiver = LeftQuiver( "*(1)[]" );
    else
        Error( "parity must be either \"Left\" or \"Right\"" );
    end;
    
    return Algebroid( PathAlgebra( R, trivial_quiver ) );
    
end );

##
@InstallMethod( ElementaryTensor,
        "for objects in algebroids",
        [ IsObjectInAlgebroid, IsObjectInAlgebroid, IsAlgebroid ],
        
  function( a, b, T )
    local product_string, a_string, b_string, product_vertex;
    
    product_vertex = PathInProductQuiver( QuiverOfAlgebra( UnderlyingQuiverAlgebra( T ) ), [ UnderlyingVertex( a ), UnderlyingVertex( b ) ] );
    product_string = StringGAP(product_vertex);
    
    return T[product_string];
    
end );

##
@InstallMethod( ElementaryTensor,
        "for object and morphism in algebroids",
        [ IsObjectInAlgebroid, IsMorphismInAlgebroid, IsAlgebroid ],
        
  function( object, morphism, T )
    local source, range, morphism_as_quiver_algebra_element, paths, coeffs,
          object_underlying_vertex, object_string, sum, i, arrows_of_path,
          mors, o, product_of_arrows_as_morphism;
    
    source = ElementaryTensor( object, Source( morphism ), T );
    range = ElementaryTensor( object, Target( morphism ), T );
    
    morphism_as_quiver_algebra_element = UnderlyingQuiverAlgebraElement( morphism );
    
    if (IsQuotientOfPathAlgebraElement( morphism_as_quiver_algebra_element ))
        
        morphism_as_quiver_algebra_element = Representative( morphism_as_quiver_algebra_element );
        
    end;
    
    if (IsZero( morphism_as_quiver_algebra_element ))
        
        return ZeroMorphism( source, range );
        
    end;
    
    paths = Paths( morphism_as_quiver_algebra_element );
    coeffs = Coefficients( morphism_as_quiver_algebra_element );
    
    object_underlying_vertex = UnderlyingVertex( object );
    object_string = StringGAP( object_underlying_vertex );
    
    sum = ZeroMorphism( source, range );
    
    for i in (1):(Length( paths ))
        
        arrows_of_path = ArrowList( paths[i] );
        
        mors = List( List( arrows_of_path,
                        b -> PathInProductQuiver( QuiverOfAlgebra( UnderlyingQuiverAlgebra( T ) ), [ object_underlying_vertex, b ] ) ),
                      b -> MorphismInAlgebroid(
                              ObjectInAlgebroid( T, Source( b ) ),
                              QuiverAlgebraElement( UnderlyingQuiverAlgebra( T ), [ 1 ], [ b ] ),
                              ObjectInAlgebroid( T, Target( b ) ) ) );
        
        if (Length( mors ) == 0)
            
            @Assert( 3, IsQuiverVertex( paths[i] ) );
            
            o = ObjectInAlgebroid( CapCategory( morphism ), paths[i] );
            
            @Assert( 3, o == Source( morphism ) && o == Target( morphism ) );
                
            product_of_arrows_as_morphism = IdentityMorphism( ElementaryTensor( object, o, T ) );
            
        else
            
            product_of_arrows_as_morphism = PreCompose( mors );
            
        end;
        
        sum = sum + coeffs[i] * product_of_arrows_as_morphism;
        
    end;
    
    return sum;
    
end );

##
@InstallMethod( ElementaryTensor,
        "for morphism and object in algebroids",
        [ IsMorphismInAlgebroid, IsObjectInAlgebroid, IsAlgebroid ],
        
  function( morphism, object, T )
    local source, range, morphism_as_quiver_algebra_element, coeffs, paths,
          object_underlying_vertex, object_string, sum, i, arrows_of_path,
          mors, o, product_of_arrows_as_morphism;
    
    source = ElementaryTensor( Source( morphism ), object, T );
    range = ElementaryTensor( Target( morphism ), object, T );
    
    morphism_as_quiver_algebra_element = UnderlyingQuiverAlgebraElement( morphism );
    
    if (IsQuotientOfPathAlgebraElement( morphism_as_quiver_algebra_element ))
        
        morphism_as_quiver_algebra_element = Representative( morphism_as_quiver_algebra_element );
        
    end;
    
    if (IsZero( morphism_as_quiver_algebra_element ))
        
        return ZeroMorphism( source, range );
        
    end;
    
    paths = Paths( morphism_as_quiver_algebra_element );
    coeffs = Coefficients( morphism_as_quiver_algebra_element );
    
    object_underlying_vertex = UnderlyingVertex( object );
    object_string = StringGAP( object_underlying_vertex );
    
    sum = ZeroMorphism( source, range );
    
    for i in (1):(Length( paths ))
        
        arrows_of_path = ArrowList( paths[ i ] );
        
        mors = List( List( arrows_of_path,
                        a -> PathInProductQuiver( QuiverOfAlgebra( UnderlyingQuiverAlgebra( T ) ), [ a, object_underlying_vertex ] ) ),
                      a -> MorphismInAlgebroid(
                              ObjectInAlgebroid( T, Source( a ) ),
                              QuiverAlgebraElement( UnderlyingQuiverAlgebra( T ), [ 1 ], [ a ] ),
                              ObjectInAlgebroid( T, Target( a ) ) ) );
        
        if (Length( mors ) == 0)
            
            @Assert( 3, IsQuiverVertex( paths[i] ) );
            
            o = ObjectInAlgebroid( CapCategory( morphism ), paths[i] );
            
            @Assert( 3, o == Source( morphism ) && o == Target( morphism ) );
            
            product_of_arrows_as_morphism = IdentityMorphism( ElementaryTensor( o, object, T ) );
            
        else
            
            product_of_arrows_as_morphism = PreCompose( mors );
            
        end;
        
        sum = sum + coeffs[i] * product_of_arrows_as_morphism;
        
    end;
    
    return sum;
    
end );

##
@InstallMethod( *,
        "for two algebroids",
        [ IsAlgebroid && HasUnderlyingQuiverAlgebra, IsAlgebroid && HasUnderlyingQuiverAlgebra ],
        
  function( A, B )

    return Algebroid( TensorProductOfAlgebras( UnderlyingQuiverAlgebra( A ), UnderlyingQuiverAlgebra( B ) ) );
    
end );

##
@InstallMethod( CapFunctor,
        "for an algebroid, two lists, a CAP Category, and a boolean",
        [ IsAlgebroid, IsList, IsList, IsCapCategory, IsBool ],
        
  function( A, images_of_objects, images_of_generating_morphisms, B, covariant )
    local kq, vertices, arrows, functor, func_obj, func_mor;
    
    kq = QuiverOfAlgebra( UnderlyingQuiverAlgebra( A ) );
    
    vertices = Vertices( kq );
    arrows = Arrows( kq );
    
    functor = @Concatenation( "Functor from ", Name( A ), " -> ", Name( B ) );
    
    functor = CapFunctor( functor, A, B );
    
    functor.ValuesOnAllObjects = images_of_objects;
    functor.ValuesOnAllGeneratingMorphisms = images_of_generating_morphisms;
    
    functor.IsContravariant = @not covariant;
    
    DeactivateCachingObject( ObjectCache( functor ) );
    DeactivateCachingObject( MorphismCache( functor ) );
    
    SetFilterObj( functor, IsAlgebroidMorphism );
    
    AddObjectFunction( functor,
      function( obj )
        local i;
        
        i = SafePosition( vertices, UnderlyingVertex( obj ) );
        
        if (IsInt( i ))
            return images_of_objects[i];
        end;
        
        Error( "vertex UnderlyingVertex( obj ) == ", UnderlyingVertex( obj ), " not found in the list ", vertices, " of vertices\n" );
        
    end );
    
    func_obj = o -> images_of_objects[SafePosition( vertices, o )];
    func_mor = a -> images_of_generating_morphisms[SafePosition( arrows, a )];
    
    if (covariant)
        
        AddMorphismFunction( functor,
          function( new_source, mor, new_range )
            local i;
            
            if (IsZero( mor ))
                return ZeroMorphism( new_source, new_range );
            end;
            
            mor = UnderlyingQuiverAlgebraElement( mor );
            
            i = Position( arrows, mor );
            
            if (IsInt( i ))
                return images_of_generating_morphisms[i];
            end;
            
            return ApplyToQuiverAlgebraElement( func_obj, func_mor, B, mor, true );
            
        end );
        
    else
        
        AddMorphismFunction( functor,
          function( new_source, mor, new_range )
            local i;
            
            if (IsZero( mor ))
                return ZeroMorphism( new_source, new_range );
            end;
            
            mor = UnderlyingQuiverAlgebraElement( mor );
            
            i = Position( arrows, mor );
            
            if (IsInt( i ))
                return images_of_objects[i];
            end;
            
            return ApplyToQuiverAlgebraElement( func_obj, func_mor, B, mor, false );
            
        end );
        
    end;
    
    return functor;
    
end );

##
@InstallMethod( CapFunctor,
        "for an algebroid, two lists, and a CAP category",
        [ IsAlgebroid, IsList, IsList, IsCapCategory ],
        
  function( A, images_of_objects, images_of_generating_morphisms, B )
    
    return CapFunctor( A, images_of_objects, images_of_generating_morphisms, B, true );
    
end );

## this a convenience method
@InstallMethod( CapFunctor,
        "for an algebroid, two records, and a boolean",
        [ IsAlgebroid, IsRecord, IsRecord, IsBool ],
        
  function( A, rec_images_of_objects, rec_images_of_generating_morphisms, covariant )
    local kq, vertices, images_of_objects, arrows, images_of_generating_morphisms,
          mor, Rq, B;
    
    kq = QuiverOfAlgebra( UnderlyingQuiverAlgebra( A ) );
    
    vertices = Vertices( kq );
    
    images_of_objects = List( vertices, v -> rec_images_of_objects[StringGAP( v ] ) );
    
    if (images_of_objects == [ ])
        Error( "the record rec_images_of_objects does not contain a named image of an object in the source category A\n" );
    end;
    
    arrows = Arrows( kq );
    
    images_of_generating_morphisms = List( arrows, a -> rec_images_of_generating_morphisms[StringGAP( a ] ) );
    
    # Construct the target category B
    if (@not IsEmpty( images_of_generating_morphisms ))
        for mor in images_of_generating_morphisms
            if (IsQuiverAlgebraElement( mor ))
                Rq = AlgebraOfElement( mor );
                B = Algebroid( Rq );
                break;
            elseif (IsCapCategoryCell( mor ))
                if (@not IsCapCategoryMorphism( mor ))
                    Error( @Concatenation( "the image ", mor, " is not a morphism"));
                end;
                B = CapCategory( mor );
                break;
            end;
        end;
    else
        B = CapCategory( images_of_objects[1] );
    end;
    
    if (@not @IsBound( B ))
        Error( "unable to extract target category from the records of images\n" );
    end;
    
    return CapFunctor( A, images_of_objects, images_of_generating_morphisms, B, covariant );
    
end );

## this a convenience method
@InstallMethod( CapFunctor,
        "for an algebroid and two records",
        [ IsAlgebroid, IsRecord, IsRecord ],
        
  function( A, rec_images_of_objects, rec_images_of_generating_morphisms )
    
    return CapFunctor( A, rec_images_of_objects, rec_images_of_generating_morphisms, true );
    
end );

##
@InstallMethod( CapFunctor,
        "for an algebroid and a CAP category object",
        [ IsFpCategory, IsCapCategoryObject ],
        
  function( A, object )
    
    return CapFunctor(
                   A,
                   ListWithIdenticalEntries( Length( SetOfObjects( A ) ), object ),
                   ListWithIdenticalEntries( Length( SetOfGeneratingMorphisms( A ) ), IdentityMorphism( object ) ),
                   CapCategory( object ) );
    
end );

##
@InstallMethod( OppositeAlgebroid,
        "for an algebroid",
        [ IsAlgebroid && HasUnderlyingQuiver ],
        
  function( A )
    local ring, over_Z, range_category, A_op;
    
    ring = CommutativeRingOfLinearCategory( A );
     
    if (IsIntegers( ring ) || ( HasIsIntegersForHomalg( ring ) && IsIntegersForHomalg( ring ) ))
        over_Z = true;
    else
        over_Z = false;
    end;
    
    if (HasRangeCategoryOfHomomorphismStructure( A ))
        range_category = RangeCategoryOfHomomorphismStructure( A );
    else
        range_category = fail;
    end;
    
    A_op = Algebroid(
                    OppositeAlgebra( UnderlyingQuiverAlgebra( A ) ),
                    over_Z; range_of_HomStructure = range_category
                    );
    
    SetOppositeAlgebroid( A_op, A );
    
    if (HasIsLinearClosureOfACategory( A ))
        SetIsLinearClosureOfACategory( A_op, IsLinearClosureOfACategory( A ) );
    end;
    
    return A_op;
    
end );

####################################
#
# methods for properties:
#
####################################

##
@InstallMethod( IsCommutative,
        "for an Algebroid",
        [ IsAlgebroid ],
     
  function( A )
    local arrows, i, j;
    
    arrows = Arrows( UnderlyingQuiverAlgebra( A ) );
    
    for i in (1):(Length(arrows))
      for j in ((i+1)):(Length(arrows))
        if (@not arrows[i]*arrows[j] == arrows[j]*arrows[i])
          return false;
        end;
      end;
    end;
    
    return true;
end );

##
@InstallMethod( NaturalTransformation,
        "for a record and two CAP functors",
        [ IsRecord, IsCapFunctor, IsCapFunctor ],
        
  function( eta, F, G )
    local vertices, images;
    
    if (NamesOfComponents( F ) == [ ])
        Error( "the record of images is empty\n" );
    end;
    
    vertices = Vertices( QuiverOfAlgebra( UnderlyingQuiverAlgebra( AsCapCategory( Source( F ) ) ) ) );
    
    images = List( vertices, v -> eta[StringGAP( v ] ) );
    
    return NaturalTransformation( F, images, G );
    
end );

##
@InstallMethod( ^,
        "for a CAP endomorphism and an integer",
        [ IsCapCategoryMorphism, IsInt ],

  function( phi, i )
    
    if (@not IsEndomorphism( phi ))
        TryNextMethod( );
    elseif (i == 0)
        return IdentityMorphism( Source( phi ) );
    elseif (i < 0)
        if (@not IsIsomorphism( phi ))
            Error( "the given endomorphism is not an isomorphism\n" );
        end;
        
        return Inverse( phi )^(-i);
    end;
    
    return PreCompose( ListWithIdenticalEntries( i, phi ) );
    
end );

@BindGlobal( "_MorphismInAlgebroid_CellAsEvaluatableString",
  function( mor, list_of_evaluatable_strings )
    local list_of_values, C, pos, cat, decomp, cmp;
    
    list_of_values = List( list_of_evaluatable_strings, EvalString );
    
    C = CapCategory( mor );
    
    pos = PositionsProperty( list_of_values, val ->
                   IsCapCategoryMorphism( val ) && IsIdenticalObj( CapCategory( val ), C ) && IsEqualForMorphismsOnMor( C, val, mor ) );
    
    if (Length( pos ) == 1)
        
        return list_of_evaluatable_strings[pos[1]];
        
    elseif (Length( pos ) > 1)
        
        # COVERAGE_IGNORE_NEXT_LINE
        Error( "the position of the morphism `mor` in `list_of_values` is not unique for mor == ", mor, "\n" );
        
    elseif (IsInt( PositionProperty( SetOfGeneratingMorphisms( C ), m -> IsEqualForMorphismsOnMor( C, m, mor ) ) ))
        
        # COVERAGE_IGNORE_NEXT_LINE
        Error( "the morphism `mor` does not lie in `list_of_values`\n" );
        
    end;
    
    pos = PositionsProperty( list_of_values, val -> IsIdenticalObj( val, C ) );
    
    if (Length( pos ) == 0)
        
        # COVERAGE_IGNORE_NEXT_LINE
        Error( "could not find CapCategory( mor ) in `list_of_values` for mor == ", mor, "\n" );
        
    elseif (Length( pos ) > 1)
        
        # COVERAGE_IGNORE_NEXT_LINE
        Error( "the position of CapCategory( mor ) in `list_of_values` is not unique for mor == ", mor, "\n" );
        
    end;
    
    cat = list_of_evaluatable_strings[pos[1]];
    
    if (CanCompute( C, "IsEqualToIdentityMorphism" ) && IsEqualToIdentityMorphism( mor ))
        
        return @Concatenation(
                       "IdentityMorphism( ", cat, ", ",
                       CellAsEvaluatableString( Source( mor ), list_of_evaluatable_strings ),
                       " )" );
        
    elseif (CanCompute( C, "IsEqualToZeroMorphism" ) && IsEqualToZeroMorphism( mor ))
        
        return @Concatenation(
                       "ZeroMorphism( ", cat, ", ",
                       CellAsEvaluatableString( Source( mor ), list_of_evaluatable_strings ), ", ",
                       CellAsEvaluatableString( Target( mor ), list_of_evaluatable_strings ), " )" );
        
    end;
    
    decomp = DecompositionOfMorphismInAlgebroid( mor );
    
    if (Length( decomp ) == 1)
        
        decomp = decomp[1];
        
        if (Length( decomp[2] ) == 1)
            
            cmp = CellAsEvaluatableString( decomp[2][1], list_of_evaluatable_strings );
            
        else
            
            cmp = @Concatenation(
                           "PreComposeList( ", cat, ", ",
                           CellAsEvaluatableString( Source( mor ), list_of_evaluatable_strings ),
                           ", [ ",
                           JoinStringsWithSeparator( List( decomp[2], gen_mor ->
                                   CellAsEvaluatableString( gen_mor, list_of_evaluatable_strings ) ), ", " ),
                           " ], ",
                           CellAsEvaluatableString( Target( mor ), list_of_evaluatable_strings ),
                           " )" );
            
        end;
        
        if (IsOne( decomp[1] ))
            
            return cmp;
            
        elseif (IsMinusOne( decomp[1] ))
            
            return @Concatenation( "AdditiveInverseForMorphisms( ", cat, ", ", cmp, " )" );
            
        end;
        
        return @Concatenation( "MultiplyWithElementOfCommutativeRingForMorphisms( ", cat, ", ", StringGAP( decomp[1] ), ", ", cmp, " )" );
        
    end;
    
    # COVERAGE_IGNORE_NEXT_LINE
    Error( "not implemented yet\n" );
    
end );

##
@InstallMethod( CellAsEvaluatableString,
        [ IsMorphismInAlgebroid, IsList ], ## @not HasHasGenesisOfCell
        
  _MorphismInAlgebroid_CellAsEvaluatableString );

####################################
#
# View, Print, and Display methods:
#
####################################

##
@InstallMethod( ViewString,
        "for an object in an algebroid",
        [ IsObjectInAlgebroid ],
        
  function( o )
    
    return @Concatenation( "<", StringView( UnderlyingVertex( o ) ), ">" );
    
end );

##
@InstallMethod( ViewString,
        "for a morphism in an algebroid",
        [ IsMorphismInAlgebroid ],
        
  function( o )
    
    if (IsRightQuiverAlgebra( UnderlyingQuiverAlgebra( CapCategory( o ) ) ))
        return @Concatenation(
                       StringView( UnderlyingVertex( Source( o ) ) ),
                       "-[",
                       StringView( UnderlyingQuiverAlgebraElement( o ) ),
                       "]->",
                       StringView( UnderlyingVertex( Target( o ) ) ) );
    else
        return @Concatenation(
                       StringView( UnderlyingVertex( Target( o ) ) ),
                       "<-[",
                       StringView( UnderlyingQuiverAlgebraElement( o ) ),
                       "]-",
                       StringView( UnderlyingVertex( Source( o ) ) ) );
    end;
    
end );

##
@InstallMethod( LaTeXOutput,
          [ IsObjectInAlgebroid ],
          
  o -> LaTeXStringForQPA( UnderlyingVertex( o ) )
);

##
@InstallMethod( LaTeXOutput,
          [ IsMorphismInAlgebroid ],
          
  function( m )
    local s;
    
    s = LaTeXStringForQPA( UnderlyingQuiverAlgebraElement( m ) );
    
    if (ValueOption( "OnlyDatum" ) == true)
      
      return s;
      
    else
      
      return @Concatenation(
                "[", LaTeXOutput( Source( m ) ), "]-\\left(",
                "[", s, "]\\right)\\rightarrow",
                "[", LaTeXOutput( Target( m ) ), "]"
              );
              
    end;
    
end );
