# SPDX-License-Identifier: GPL-2.0-or-later
# Algebroids: Algebroids and bialgebroids as preadditive categories generated by enhanced quivers
#
# Implementations
#

##
@InstallMethod( CategoryOfVectorSpaces,
        [ IsFieldForHomalg ],
        
  function( F )
    
    return CategoryOfVectorSpaces( F.ring );
    
end );

##
@InstallMethod( MatrixByRows,
        [ IsFieldForHomalg, IsDenseList, IsDenseList ],
        
  function( F, dimensions, mat )
    
    return MatrixByRows( F.ring, dimensions, mat );
    
end );

##
@InstallMethod( MatrixByRows,
        [ IsFieldForHomalg, IsList ],
        
  function( F, mat )
    
    return MatrixByRows( F.ring, mat );
    
end );


##
@InstallMethod( MatrixByCols,
        [ IsFieldForHomalg, IsDenseList, IsDenseList ],
        
  function( F, dimensions, mat )
    
    return MatrixByCols( F.ring, dimensions, mat );
    
end );

##
@InstallMethod( MatrixByCols,
        [ IsFieldForHomalg, IsList ],
        
  function( F, mat )
    
    return MatrixByCols( F.ring, mat );
    
end );

##
@InstallMethod( EmptyVector,
        [ IsFieldForHomalg ],
  
  function( F )
    
    return EmptyVector( F.ring );
    
end );

