# SPDX-License-Identifier: GPL-2.0-or-later
# Algebroids: Algebroids and bialgebroids as preadditive categories generated by enhanced quivers
#
# Implementations
#

####################################
##
## Constructors
##
####################################

##
@InstallMethod( QuiverRows,
               [ IsQuiverAlgebra ],
               
  function( underlying_quiver_algebra )
    
    return QuiverRows( underlying_quiver_algebra, false );
    
end );

##
@InstallMethod( QuiverRowsDescentToZDefinedByBasisPaths,
               [ IsQuiverAlgebra ],
               
  function( underlying_quiver_algebra )
    
    return QuiverRows( underlying_quiver_algebra, true );
    
end );

##
@InstallMethod( QuiverRowsDescentToZDefinedByBasisPaths,
               [ IsQuiverRowsCategory ],
               
  function( quiver_rows )
    local underlying_quiver_algebra;
    
    underlying_quiver_algebra = UnderlyingQuiverAlgebra( quiver_rows );
    
    return QuiverRows( underlying_quiver_algebra, true );
    
end );

##
@InstallMethod( QuiverRows,
               [ IsQuiverAlgebra, IsBool ],
               
  function( underlying_quiver_algebra, over_Z )
    local underlying_quiver, category, ring, paths, p, q, category_name;
    
    if (@not IsFiniteDimensional( underlying_quiver_algebra ))
        
        Error( "the given quiver has to be finite dimensional\n" );
        
    end;
    
    ring = LeftActingDomain( underlying_quiver_algebra );
    
    if (over_Z)
        
        if (IsIdenticalObj( ring, Rationals )
           ||
           ( HasIsRationalsForHomalg( ring ) && IsRationalsForHomalg( ring )
             && @not IsHomalgExternalRingRep( ring ) )
       )
            
            ## Test if the multiplication table which is induced by the basis of the quiver algebra
            ## (computed by the Groebner basis) only has integral coefficients.
            paths = BasisPaths( CanonicalBasis( underlying_quiver_algebra ) );
            
            for p in paths
                
                for q in paths
                    
                    if (@not ForAll( Coefficients( PathAsAlgebraElement( underlying_quiver_algebra, p ) * PathAsAlgebraElement( underlying_quiver_algebra, q ) ), IsInt ))
                        
                        Error( "the basis of the given quiver algebra does give rise to a well-defined algebroid over Z\n");
                        
                    end;
                    
                end;
                
            end;
            
        else
            
            Error( "the left acting domain of the given quiver algebra is not supported for constructing an algebroid of the integers\n");
            
        end;
        
        ring = HomalgRingOfIntegers();
        
        category_name = @Concatenation( "QuiverRows( ", StringGAP( underlying_quiver_algebra )," ) descended to Z" );
        
    else
        
        category_name = @Concatenation( "QuiverRows( ", StringGAP( underlying_quiver_algebra )," )" );
        
    end;
    
    underlying_quiver = QuiverOfAlgebra( underlying_quiver_algebra );
    
    category = CreateCapCategory( category_name,
                        IsQuiverRowsCategory,
                        IsQuiverRowsObject,
                        IsQuiverRowsMorphism && HasMorphismMatrix,
                        IsCapCategoryTwoCell );
    
    DeactivateCachingOfCategory( category );
    
    CapCategorySwitchLogicOff( category );
    
    SetIsAdditiveCategory( category, true );
    
    SetIsLinearCategoryOverCommutativeRing( category, true );
    
    SetCommutativeRingOfLinearCategory( category, ring );
    
    SetUnderlyingQuiverAlgebra( category, underlying_quiver_algebra );
    
    SetUnderlyingQuiver( category, underlying_quiver );
    
    INSTALL_FUNCTIONS_FOR_QUIVER_ROWS( category, over_Z );
    
    Finalize( category );
    
    return category;
    
end );

##
@InstallMethod( QuiverRowsObject,
               [ IsList, IsQuiverRowsCategory ],
               
  function( list_of_vertices, category )
    local quiver_rows_object, s, L, v, vertex, current;
    
    ## create normal form of list_of_vertices
    ## every object will be constructed via this constructor, thus,
    ## every object can be assumed to be in normal form
    ## [ [ vertex, multiplicity ], ... ]
    ## multiplicites > 0
    
    ## get rid of zeros (and negative integers)
    list_of_vertices = Filtered( list_of_vertices, l -> IsPosInt( l[2] ) );
    
    ## collect consecutive vertices
    s = Size( list_of_vertices );
    
    if (s > 1)
        
        L = [];
        
        current = ShallowCopy( list_of_vertices[1] );
        
        for v in (2):(s)
            
            vertex = list_of_vertices[v];
            
            if (vertex[1] == current[1])
                
                current[2] = current[2] + vertex[2];
                
            else
                
                Add( L, current );
                
                current = ShallowCopy( vertex );
                
            end;
            
        end;
        
        Add( L, current );
        
    else
        
        L = list_of_vertices;
        
    end;
    
    quiver_rows_object = CreateCapCategoryObjectWithAttributes(
                              category,
                              ListOfQuiverVertices, L );

    Add( category, quiver_rows_object );
    
    return quiver_rows_object;
    
end );

##
@InstallMethod( QuiverRowsMorphism,
               [ IsQuiverRowsObject, IsList, IsQuiverRowsObject ],
               
  function( source, matrix, range )
    local quiver_rows_morphism, category;
    
    category = CapCategory( source );

    quiver_rows_morphism = CreateCapCategoryMorphismWithAttributes(
                                category,
                                source,
                                range,
                                MorphismMatrix, matrix );

    Add( category, quiver_rows_morphism );
    
    return quiver_rows_morphism;
    
end );

##
@InstallMethod( AsQuiverRowsObject,
               [ IsQuiverVertex, IsQuiverRowsCategory ],
               
  function( v, category )
    
    return QuiverRowsObject( [ [ v, 1 ] ], category );
    
end );

##
@InstallMethod( AsQuiverRowsMorphism,
               [ IsQuiverAlgebraElement, IsQuiverRowsCategory ],
               
  function( m, category )
    local v, w, m_rep;
    
    if (IsZero( m ))
        
        Error( "cannot create a morphism form 0 since the information about source and range is not deducable\n" );
        
    end;
    
    if (@not IsUniform( m ))
        
        Error( "the given element is not uniform\n" );
        
    end;
    
    if (IsQuotientOfPathAlgebraElement( m ))
        
        m_rep = Representative( m );
        
    else
        
        m_rep = m;
        
    end;
    
    v = Source( LeadingPath( m_rep ) );
    
    w = Target( LeadingPath( m_rep ) );
    
    return QuiverRowsMorphism( AsQuiverRowsObject( v, category ), [ [ m ] ], AsQuiverRowsObject( w, category ) );
    
end );

##
@InstallMethod( NrRows,
               [ IsQuiverRowsMorphism ],
               
  function( morphism )
    
    return NrSummands( Source( morphism ) );
    
end );

##
@InstallMethod( NrCols,
               [ IsQuiverRowsMorphism ],
               
  function( morphism )
    
    return NrSummands( Target( morphism ) );
    
end );

##
@InstallMethod( getindex,
               [ IsQuiverRowsMorphism, IsInt ],
               
  function( morphism, i )
    local nr_cols, mat, zero;
    
    if (!( i >= 1 ) && ( i <= NrRows( morphism ) ))
        
        Error( "bad index" );
        
    end;
    
    nr_cols = NrCols( morphism );
    
    if (nr_cols == 0)
        
        return [ ];
        
    end;
    
    mat = MorphismMatrix( morphism );
    
    zero = Zero( UnderlyingQuiverAlgebra( CapCategory( morphism ) ) );
    
    if (IsEmpty( mat ))
        
        return List( (1):(nr_cols), i -> zero );
        
    end;
    
    return mat[i];
    
end );

##
@InstallMethod( NrSummands,
               [ IsQuiverRowsObject ],
               
    function( object )
      
      return Sum( List( ListOfQuiverVertices( object ), l -> l[2] ) );
      
end );

##
@InstallMethod( getindex,
               [ IsQuiverRowsObject, IsInt ],
               
  function( object, i )
    local list, current, l;
    
    if (!( ( i >= 1 ) && ( i <= NrSummands( object ) ) ))
        
        Error( "bad index" );
        
    end;
    
    list = ListOfQuiverVertices( object );
    
    current = 0;
    
    for l in list
        
        current = current + l[2];
        
        if (current >= i)
            
            return l[1];
            
        end;
        
    end;
    
    Error( "Bug in []-Operator for IsQuiverRowsObject" );
    
end );

##
@InstallMethod( AsListListOfMatrices,
                [ IsQuiverRowsMorphism ],
  function( alpha )
    local list_source, list_range, row_intervals, boundary, i, col_intervals, listlist, intr, intc, mat, row;
    
    list_source = ListOfQuiverVertices( Source( alpha ) );
    
    if (IsEmpty( list_source ))
        
        return [];
        
    end;
    
    list_range = ListOfQuiverVertices( Target( alpha ) );
    
    if (IsEmpty( list_range ))
        
        return [];
        
    end;
    
    row_intervals = [];
    
    boundary = 1;
    
    for i in (1):(Size( list_source ))
        
        row_intervals[i] = (boundary):(boundary + (list_source[i][2] - 1) );
        
        boundary = boundary + list_source[i][2];
        
    end;
    
    col_intervals = [];
    
    boundary = 1;
    
    for i in (1):(Size( list_range ))
        
        col_intervals[i] = (boundary):(boundary + (list_range[i][2] - 1) );
        
        boundary = boundary + list_range[i][2];
        
    end;
    
    mat = MorphismMatrix( alpha );
    
    listlist = [];
    
    for intr in row_intervals
        
        row = [];
        
        for intc in col_intervals
            
            Add( row, List( mat[intr], r -> r[intc] ) );
            
        end;
        
        Add( listlist, row );
        
    end;
    
    return listlist;
    
end );

##
@InstallMethod( PermutationToSortedRepresentative,
               [ IsQuiverRowsObject ],
               
  function( object )
    local list;
    
    list = ListOfQuiverVertices( object );
    
    return SortingPerm( List( list, l -> l[1] ) );
    
end );

##
@InstallMethod( SortedRepresentative,
               [ IsQuiverRowsObject ],
                
  function( object )
    local perm, list;
    
    perm = PermutationToSortedRepresentative( object );
    
    list = ListOfQuiverVertices( object );
    
    return QuiverRowsObject( Permuted( list, perm ), CapCategory( object ) );
    
end );

####################################
##
## Basic operations
##
####################################


@InstallGlobalFunction( INSTALL_FUNCTIONS_FOR_QUIVER_ROWS,
  
  function( category, over_Z )
    local algebra, quiver, zero, IDENTITY_MATRIX_QUIVER_ROWS, ZERO_MATRIX_QUIVER_ROWS,
          vertices, basis, basis_paths_by_vertex_index, path, MATRIX_FOR_ALGEBROID_HOMSTRUCTURE, hom_structure_algebroid,
          ring, default_range_of_HomStructure, hom_structure_range_category, hom_structure_on_morphisms_for_pure_components,
          representative_func;
    
    algebra = UnderlyingQuiverAlgebra( category );
    
    ring = CommutativeRingOfLinearCategory( category );
    
    quiver = UnderlyingQuiver( category );
    
    zero = Zero( algebra );
    
    ## prepare the homomorphism structure
    
    ## storing the basis paths
    ## basis_paths_by_vertex_index[ v_index ][ w_index ] == [ p_1:v -> w, p_2:v -> w, ... ]
    vertices = Vertices( quiver );
    
    basis = BasisPaths( CanonicalBasis( algebra ) );
    
    basis_paths_by_vertex_index = List( vertices, i -> List( vertices, i -> [ ] ) );
    
    for path in basis
        
        Add( basis_paths_by_vertex_index[ VertexIndex( Source( path ) ) ][ VertexIndex( Target( path ) ) ], path );
        
    end;
    
    ## precomputing matrices for the hom structure of the algebroid
    ## hom_structure_algebroid[ v_index ][ w_index ][ v'_index ][ w'_index ][ path_1_index ][ path_2_index ] == [ Hom(v,w) -> Hom(v',w'): x -> path_1 * x * path_2 ]
    ## in particular: (path_1: v' -> v), (path_2: w -> w')
    
    MATRIX_FOR_ALGEBROID_HOMSTRUCTURE = function( v, w, vp, wp, path_1, path_2 )
        local mat, hom_v_w, hom_vp_wp, alpha, beta, path;
        
        mat = [];
        
        hom_v_w = basis_paths_by_vertex_index[ VertexIndex( v ) ][ VertexIndex( w ) ];
        
        if (IsEmpty( hom_v_w ))
            
            return mat;
            
        end;
        
        hom_vp_wp = basis_paths_by_vertex_index[ VertexIndex( vp ) ][ VertexIndex( wp ) ];
        
        if (IsEmpty( hom_vp_wp ))
            
            return mat;
            
        end;
        
        alpha = PathAsAlgebraElement( algebra, path_1 );
        
        beta = PathAsAlgebraElement( algebra, path_2 );
        
        if (IsQuotientOfPathAlgebra( algebra ))
            
            for path in hom_v_w
                
                Add( mat,
                  CoefficientsOfPaths( hom_vp_wp, Representative( alpha * PathAsAlgebraElement( algebra, path ) * beta ) )
                );
                
            end;
            
        else
            
            for path in hom_v_w
                
                Add( mat,
                  CoefficientsOfPaths( hom_vp_wp, ( alpha * PathAsAlgebraElement( algebra, path ) * beta ) )
                );
                
            end;
            
        end;
        
        return mat;
        
    end;
    
    hom_structure_algebroid =
        List( vertices, v ->
            List( vertices, w ->
                List( vertices, vp ->
                    List( vertices, wp ->
                        List( basis_paths_by_vertex_index[ VertexIndex( vp ) ][ VertexIndex( v ) ], path_1 ->
                            List( basis_paths_by_vertex_index[ VertexIndex( w ) ][ VertexIndex( wp ) ], path_2 ->
                                MATRIX_FOR_ALGEBROID_HOMSTRUCTURE( v, w, vp, wp, path_1, path_2 )
                            )
                        )
                    )
                )
            )
        );
    
    default_range_of_HomStructure = CategoryOfRows( ring );
    
    hom_structure_range_category = CAP_INTERNAL_RETURN_OPTION_OR_DEFAULT( "range_of_HomStructure", default_range_of_HomStructure );
    
    if (!(IsCategoryOfRows( hom_structure_range_category ) || (IsBoundGlobal( "IsMatrixCategory" ) && ValueGlobal( "IsMatrixCategory" )( hom_structure_range_category ))))
        
        Error( "range_of_HomStructure must be a category of rows or a matrix category" );
        
    end;
    
    SetRangeCategoryOfHomomorphismStructure( category, hom_structure_range_category );
    
    ##
    if (IsQuotientOfPathAlgebra( algebra ))
        
        representative_func = Representative;
        
    else
        
        representative_func = IdFunc;
        
    end;
    
    ##
    ZERO_MATRIX_QUIVER_ROWS = function( nr_rows, nr_cols )
        
        if (nr_rows == 0 || nr_cols == 0)
            
            return [];
            
        end;
        
        return NullMat( nr_rows, nr_cols, algebra );
        
    end;
    
    ##
    IDENTITY_MATRIX_QUIVER_ROWS = function( object )
        local size, list, l, mat, row, counter, v, id, j;
        
        size = NrSummands( object );
        
        if (size == 0)
            
            return [];
            
        end;
        
        list = ListOfQuiverVertices( object );
        
        mat = [];
        
        counter = 1;
        
        for l in list
            
            v = l[1];
            
            id = PathAsAlgebraElement( algebra, v );
            
            for j in (counter):(counter + (l[2] - 1))
                
                row = List( (1):(size), i -> zero );
                
                row[j] = id;
                
                Add( mat, row );
                
            end;
            
            counter = counter + l[2];
            
        end;
        
        return mat;
        
    end;
    
    ## Well-defined for objects and morphisms
    ##
    AddIsWellDefinedForObjects( category,
      function( cat, object )
        local list;
        
        list = ListOfQuiverVertices( object );
        
        if (IsEmpty( list ))
            
            return true;
            
        end;
        
        if (@not ForAll( list, l -> IsList( l ) && Size( l ) == 2 ))
            
            return false;
            
        end;
        
        if (@not ForAll( list, l -> IsQuiverVertex( l[1] ) && IsPosInt( l[2] ) ))
            
            return false;
            
        end;
        
        if (@not ForAll( list, l -> l[1] in quiver ))
            
            return false;
            
        end;
        
        # all tests passed, so it is well-defined
        return true;
        
    end );
    
    ##
    AddIsWellDefinedForMorphisms( category,
      function( cat, morphism )
        local matrix, nr_rows, nr_cols, source, range, i, j, m, v, w;
        
        matrix = MorphismMatrix( morphism );
        
        nr_rows = NrRows( morphism );
        
        nr_cols = NrCols( morphism );
        
        if (nr_rows == 0 || nr_cols == 0)
            
            return IsEmpty( matrix );
            
        end;
        
        if (@not Size( matrix ) == nr_rows)
            
            return false;
            
        end;
        
        if (@not ForAll( matrix, row -> Size( row ) == nr_cols ))
            
            return false;
            
        end;
        
        source = Source( morphism );
        
        range = Target( morphism );
        
        for i in (1):(nr_rows)
            
            for j in (1):(nr_cols)
                
                m = matrix[i][j];
                
                ##TODO: in operator does not distinguish between quotient and non-quotient algebra
                if (!(m in algebra))
                    Print( "1");
                    return false;
                    
                end;
                
                if (@not IsZero( m ))
                    
                    if (@not IsUniform( m ))
                        
                        return false;
                        
                    end;
                    
                    if (IsQuotientOfPathAlgebraElement( m ))
                        
                        m = Representative( m );
                        
                    end;
                    
                    v = Source( LeadingPath( m ) ); 
                        
                    if (!( source[i] == v ))
                        
                        return false;
                        
                    end;
                    
                    w = Target( LeadingPath( m ) );
                    
                    if (!( range[j] == w ))
                        
                        return false;
                        
                    end;
                    
                    if (over_Z && @not ForAll( Coefficients( m ), IsInt ))
                        
                        return false;
                        
                    end;
                end;
                
            end;
            
        end;
        
        # all tests passed, so it is well-defined
        return true;
        
    end );
    
    ## Equality Basic Operations for Objects and Morphisms
    ##
    AddIsEqualForObjects( category,
      function( cat, A, B )
        
        return ListOfQuiverVertices( A ) == ListOfQuiverVertices( B );
      
    end );
    
    ##
    AddIsCongruentForMorphisms( category,
      function( cat, alpha, beta )
        
        return MorphismMatrix( alpha ) == MorphismMatrix( beta );
        
    end );
    
    ##
    AddAdditiveGenerators( category,
      function( cat )
        
        return List( Vertices( UnderlyingQuiver( category ) ), v -> AsQuiverRowsObject( v, category ) );
        
    end );
    
    ## Basic Operations for a Category
    
    ##
    AddIdentityMorphism( category,
      
      function( cat, object )
        
        return QuiverRowsMorphism( object, IDENTITY_MATRIX_QUIVER_ROWS( object ), object );
        
    end );
    
    ##
    AddZeroMorphism( category,
      function( cat, source, range )
        
        return QuiverRowsMorphism( source, ZERO_MATRIX_QUIVER_ROWS( NrSummands( source ), NrSummands( range ) ), range );
        
    end );
    
    ##
    AddPreCompose( category,
      function( cat, alpha, beta )
        local A, B, C, mat;
        
        A = Source( alpha );
        
        B = Target( alpha );
        
        C = Target( beta );
        
        if (NrSummands( A ) == 0 || NrSummands( B ) == 0 || NrSummands( C ) == 0)
            
            return ZeroMorphism( A, C );
            
        end;
        
        mat = MorphismMatrix( alpha ) * MorphismMatrix( beta );
        
        return QuiverRowsMorphism( A, mat, C );
        
    end );
    
    #
    AddMultiplyWithElementOfCommutativeRingForMorphisms( category,
      function( cat, r, morphism )
        
        return QuiverRowsMorphism( Source( morphism ), r * MorphismMatrix( morphism ), Target( morphism ) );
        
    end );
    
    ## Basic Operations for an Additive Category
    ##
    AddIsZeroForMorphisms( category,
      function( cat, alpha )
        local matrix, r, c;
        
        matrix = MorphismMatrix( alpha );
        
        if (IsEmpty( matrix ))
            
            return true;
            
        end;
        
        for r in matrix
            
            for c in r
                
                if (@not IsZero( c ))
                    
                    return false;
                    
                end;
                
            end;
            
        end;
        
        return true;
        
    end );
    
    ##
    AddAdditionForMorphisms( category,
      function( cat, alpha, beta )
        
        return QuiverRowsMorphism( Source( alpha ),
                                   MorphismMatrix( alpha ) + MorphismMatrix( beta ),
                                   Target( beta ) );
        
    end );
    
    ##
    AddAdditiveInverseForMorphisms( category,
      function( cat, alpha )
        
        return QuiverRowsMorphism( Source( alpha ),
                                   -MorphismMatrix( alpha ),
                                   Target( alpha ) );
        
    end );
    
    ##
    AddZeroObject( category,
      function( cat )
        
        return QuiverRowsObject( [ ], category );
        
    end );
    
    ##
    AddUniversalMorphismIntoZeroObjectWithGivenZeroObject( category,
      function( cat, sink, zero_object )
        
        return QuiverRowsMorphism( sink, [ ], zero_object );
        
    end );
    
    ##
    AddUniversalMorphismFromZeroObjectWithGivenZeroObject( category,
      function( cat, source, zero_object )
        
        return QuiverRowsMorphism( zero_object, [ ], source );
        
    end );
    
    ##
    AddDirectSum( category,
      function( cat, list )
        
        return QuiverRowsObject( @Concatenation( List( list, ListOfQuiverVertices ) ), category );
        
    end );
    
    ##
    AddProjectionInFactorOfDirectSumWithGivenDirectSum( category,
      function( cat, list, projection_number, direct_sum_object )
        local range, nr_cols, pre_matrix, id_matrix, post_matrix;
        
        range = list[projection_number];
        
        nr_cols = NrSummands( range );
        
        if (NrSummands( direct_sum_object ) == 0 || nr_cols == 0)
            
            return QuiverRowsMorphism( direct_sum_object, [], range );
            
        end;
        
        pre_matrix = 
            ZERO_MATRIX_QUIVER_ROWS( 
                Sum( list[ (1):(projection_number - 1) ], i -> NrSummands( i ) ),
                nr_cols
            );
        
        id_matrix = IDENTITY_MATRIX_QUIVER_ROWS( range );
        
        post_matrix = 
            ZERO_MATRIX_QUIVER_ROWS( 
                Sum( list[ [projection_number + 1 .. Size( list ) ] ], i -> NrSummands( i ) ),
                nr_cols
            );
        
        return QuiverRowsMorphism( direct_sum_object,
                                   @Concatenation( pre_matrix, id_matrix, post_matrix ),
                                   range );
        
    end );
    
    ##
    AddInjectionOfCofactorOfDirectSumWithGivenDirectSum( category,
      function( cat, list, injection_number, direct_sum_object )
        local source, nr_cols, pre_matrix, id_matrix, post_matrix;
        
        source = list[injection_number];
        
        nr_cols = NrSummands( source );
        
        if (NrSummands( direct_sum_object ) == 0 || nr_cols == 0)
            
            return QuiverRowsMorphism( source, [], direct_sum_object );
            
        end;
        
        pre_matrix = 
            ZERO_MATRIX_QUIVER_ROWS( 
                Sum( list[ (1):(injection_number - 1) ], i -> NrSummands( i ) ),
                nr_cols
            );
        
        id_matrix = IDENTITY_MATRIX_QUIVER_ROWS( source );
        
        post_matrix = 
            ZERO_MATRIX_QUIVER_ROWS( 
                Sum( list[ [injection_number + 1 .. Size( list ) ] ], i -> NrSummands( i ) ),
                nr_cols
            );
        
        return QuiverRowsMorphism( source,
                                   Transpose( @Concatenation( pre_matrix, id_matrix, post_matrix ) ),
                                   direct_sum_object );
        
    end );
    
    # ##
    AddUniversalMorphismIntoDirectSumWithGivenDirectSum( category,
      function( cat, diagram, test_object, source, direct_sum )
        local mat, nr_rows;
        
        nr_rows = NrSummands( test_object );
        
        if (NrSummands( direct_sum ) == 0 || nr_rows == 0)
            
            return QuiverRowsMorphism( test_object, [], direct_sum );
            
        end;
        
        mat = List( (1):(nr_rows), i -> @Concatenation( List( source, tau -> tau[i] ) ) );
        
        return QuiverRowsMorphism( test_object, mat, direct_sum );
        
    end );
    
    ##
    AddUniversalMorphismFromDirectSumWithGivenDirectSum( category,
      function( cat, diagram, test_object, sink, direct_sum )
        local mat;
        
        if (NrSummands( direct_sum ) == 0 || NrSummands( test_object ) == 0)
            
            return QuiverRowsMorphism( direct_sum, [], test_object );
            
        end;
        
        mat = @Concatenation( List( sink, MorphismMatrix ) );
        
        return QuiverRowsMorphism( direct_sum, mat, test_object );
        
    end );
    
    ##
    AddHomomorphismStructureOnObjects( category,
      function( cat, A, B )
        local listA, listB, rank, a, b;
        
        listA = ListOfQuiverVertices( A );
        
        listB = ListOfQuiverVertices( B );
        
        rank = 0;
        
        for a in listA
            
            for b in listB
                
                rank = rank + Size( basis_paths_by_vertex_index[ VertexIndex( a[1] ) ][ VertexIndex( b[1] ) ] ) * a[2] * b[2] ;
                
            end;
            
        end;
        
        return ObjectConstructor( hom_structure_range_category, rank );
        
    end );
    
    ## expects only non-zero cases
    hom_structure_on_morphisms_for_pure_components = function( alpha, beta, listi, listj, listk, listl )
        local j, k, i, l, a, b, c, d, alpha_ij, beta_kl, row, entry, row_counts, col_counts,
              basis_vp_v, basis_w_wp, basis_v_w, m, basis_vp_wp, n, mat, vp, v, w, wp, coeffs_alpha, coeffs_beta, p, q;
        
        a = listj[2];
        
        b = listk[2];
        
        c = listi[2];
        
        d = listl[2];
        
        vp = listi[1];
        
        v = listj[1];
        
        w = listk[1];
        
        wp = listl[1];
        
        basis_vp_v = basis_paths_by_vertex_index[ VertexIndex(vp) ][ VertexIndex( v )];
        
        basis_w_wp = basis_paths_by_vertex_index[ VertexIndex(w) ][ VertexIndex( wp )];
        
        basis_v_w = basis_paths_by_vertex_index[ VertexIndex(v) ][ VertexIndex( w )];
        
        m = Size( basis_v_w );
        
        basis_vp_wp = basis_paths_by_vertex_index[ VertexIndex(vp) ][ VertexIndex( wp )];
        
        n = Size( basis_vp_wp );
        
        mat = [];
        
        for j in (1):(a)
            
            for k in (1):(b)
                
                row = [];
                
                for i in (1):(c)
                    
                    for l in (1):(d)
                        
                        ## create dummy zero mat
                        entry = NullMat( m, n );
                        
                        alpha_ij = alpha[i][j];
                        
                        if (@not IsZero( alpha_ij ))
                            
                            beta_kl = beta[k][l];
                            
                            if (@not IsZero( beta_kl ))
                                
                                coeffs_alpha = CoefficientsOfPaths( basis_vp_v, alpha_ij );
                                
                                coeffs_beta = CoefficientsOfPaths( basis_w_wp, beta_kl );
                                
                                for p in (1):(Size( basis_vp_v ))
                                    
                                    for q in (1):(Size( basis_w_wp ))
                                        
                                        entry = entry + 
                                            coeffs_alpha[p] * coeffs_beta[q] *
                                            hom_structure_algebroid[ VertexIndex(v) ][ VertexIndex(w) ][ VertexIndex(vp) ][ VertexIndex(wp) ][ p ][ q ];
                                        
                                    end;
                                    
                                end;
                                
                            end;
                            
                        end;
                        
                        Add( row, entry );
                        
                    end;
                    
                end;
                
                Add( mat, row );
                
            end;
            
        end;
        
        row_counts = List( mat, r -> Size( r[1] ) );
        
        col_counts = List( mat[1], m -> Size( m[1] ) );
        
        return CAP_INTERNAL_MORPHISM_BETWEEN_DIRECT_SUMS_LIST_LIST( row_counts, mat, col_counts );
        
    end;
    
    ##
    AddHomomorphismStructureOnMorphismsWithGivenObjects( category,
      function( cat, hom_source, alpha, beta, hom_range )
        local listj, listk, listi, listl, listjk, listil, mat, j, k, row, i, l, row_counts, col_counts, alpham, betam, entry;
        
        listi = ListOfQuiverVertices( Source( alpha ) );
        
        listj = ListOfQuiverVertices( Target( alpha ) );
        
        listk = ListOfQuiverVertices( Source( beta ) );
        
        listl = ListOfQuiverVertices( Target( beta ) );
        
        ##
        row_counts = [];
        
        for j in (1):(Size( listj ))
            
            for k in (1):(Size( listk ))
                
                Add( row_counts, listj[j][2] * listk[k][2] * Size( basis_paths_by_vertex_index[ VertexIndex( listj[j][1] ) ][ VertexIndex( listk[k][1] ) ] ) );
                
            end;
            
        end;
        
        col_counts = [];
        
        for i in (1):(Size( listi ))
            
            for l in (1):(Size( listl ))
                
                Add( col_counts, listi[i][2] * listl[l][2] * Size( basis_paths_by_vertex_index[ VertexIndex( listi[i][1] ) ][ VertexIndex( listl[l][1] ) ] ) );
                
            end;
            
        end;
        
        ##
        alpham = AsListListOfMatrices( alpha );
        
        betam = AsListListOfMatrices( beta );
        
        mat = [];
        
        for j in (1):(Size( listj ))
            
            for k in (1):(Size( listk ))
                
                row = [];
                
                if (row_counts[(j-1)*Size( listk ) + k] > 0)
                    
                    for i in (1):(Size( listi ))
                        
                        for l in (1):(Size( listl ))
                            
                            entry = [];
                            
                            if (col_counts[(i-1)*Size( listl ) + l] > 0)
                                
                                entry = hom_structure_on_morphisms_for_pure_components(
                                    alpham[i][j], betam[k][l], listi[i], listj[j], listk[k], listl[l]
                                );
                                
                            end;
                            
                            Add( row, entry );
                            
                        end;
                        
                    end;
                    
                end;
                
                Add( mat, row );
                
            end;
            
        end;
        
        mat = CAP_INTERNAL_MORPHISM_BETWEEN_DIRECT_SUMS_LIST_LIST(
            row_counts, mat, col_counts
        );
        
        if (IsEmpty( mat ))
            
            return ZeroMorphism( hom_structure_range_category, hom_source, hom_range );
            
        else
            
            return MorphismConstructor( hom_structure_range_category, hom_source, HomalgMatrix( mat, ObjectDatum( hom_structure_range_category, hom_source ), ObjectDatum( hom_structure_range_category, hom_range ), ring ), hom_range );
            
        end;
        
    end );
    
    ##
    AddDistinguishedObjectOfHomomorphismStructure( category,
      function( cat )
        
        return ObjectConstructor( hom_structure_range_category, 1 );
        
    end );
    
    ##
    AddInterpretMorphismAsMorphismFromDistinguishedObjectToHomomorphismStructureWithGivenObjects( category,
      function( cat, source, alpha, range )
        local listlist, lists, listr, row, i, j, submat, basis, c, a;
        
        listlist = AsListListOfMatrices( alpha );
        
        lists = ListOfQuiverVertices( Source( alpha ) );
        
        listr = ListOfQuiverVertices( Target( alpha ) );
        
        row = [];
        
        for i in (1):(Size( lists ))
            
            for j in (1):(Size( listr ))
                
                submat = listlist[i][j];
                
                basis = basis_paths_by_vertex_index[ VertexIndex( lists[i][1] ) ][ VertexIndex( listr[j][1] ) ];
                
                for c in (1):(lists[i][2] )
                    
                    for a in (1):(listr[j][2] )
                        
                        Append( row, CoefficientsOfPaths( basis, representative_func( submat[c][a] ) ) );
                        
                    end;
                    
                end;
                
            end;
            
        end;
        
        if (IsEmpty( row ))
            
            return ZeroMorphism( hom_structure_range_category, source, range );
            
        else
            
            return MorphismConstructor( hom_structure_range_category, source, HomalgMatrix( row, 1, Size( row ), ring ), range );
            
        end;
        
    end );
    
    ##
    AddInterpretMorphismFromDistinguishedObjectToHomomorphismStructureAsMorphism( category,
      function( cat, A, B, morphism )
        local coeffs, lists, listr, mat, pos, i, row, j, submat, basis, c, submatrow, a,
              entry, row_counts, col_counts;
        
        ## this works for range categories with attribute UnderlyingMatrix
        coeffs = EntriesOfHomalgMatrix( UnderlyingMatrix( morphism ) );
        
        lists = ListOfQuiverVertices( A );
        
        listr = ListOfQuiverVertices( B );
        
        mat = [];
        
        pos = 1;
        
        for i in (1):(Size( lists ))
            
            row = [];
            
            for j in (1):(Size( listr ))
                
                submat = [];
                
                basis = basis_paths_by_vertex_index[ VertexIndex( lists[i][1] ) ][ VertexIndex( listr[j][1] ) ];
                
                for c in (1):(lists[i][2] )
                    
                    submatrow = [];
                    
                    for a in (1):(listr[j][2] )
                        
                        entry = coeffs[ (pos):(pos + ( Size( basis ) - 1 )) ];
                        
                        entry = QuiverAlgebraElement( algebra, entry, basis );
                        
                        Add( submatrow, entry );
                        
                        pos = pos + Size( basis );
                        
                    end;
                    
                    Add( submat, submatrow );
                    
                end;
                
                Add( row, submat );
                
            end;
            
            Add( mat, row );
            
        end;
        
        row_counts = List( lists, i -> i[2] );
        
        col_counts = List( listr, i -> i[2] );
        
        mat = CAP_INTERNAL_MORPHISM_BETWEEN_DIRECT_SUMS_LIST_LIST(
            row_counts, mat, col_counts
        );
        
        return QuiverRowsMorphism( A, mat, B );
        
    end );
    
end );


####################################
##
## Helper
##
####################################

@InstallGlobalFunction( CAP_INTERNAL_MORPHISM_BETWEEN_DIRECT_SUMS_LIST_LIST,
  function( row_counts, matrix, col_counts )
    local nr_rows, nr_cols, row_count_indices, col_count_indices, result_mat, r;
    
    nr_rows = Size( row_counts );
    
    nr_cols = Size( col_counts );
    
    row_count_indices = Filtered( (1):(nr_rows), i -> row_counts[i] > 0 );
    
    if (IsEmpty( row_count_indices ))
        
        return [];
        
    end;
    
    col_count_indices = Filtered( (1):(nr_cols), i -> col_counts[i] > 0 );
    
    if (IsEmpty( col_count_indices ))
        
        return [];
        
    end;
    
    matrix = matrix[row_count_indices];
    
    matrix = List( matrix, r -> r[col_count_indices] );
    
    nr_rows = Size( row_count_indices );
    
    nr_cols = Size( col_count_indices );
    
    result_mat = [];
    
    for r in (1):(nr_rows)
        
        Append( result_mat,
                List( [ 1 .. row_counts[row_count_indices[r]] ],
                i -> @Concatenation( List( matrix[r], mat -> mat[i] ) ) )
        );
        
    end;
    
    return result_mat;
    
end );

####################################
##
## View
##
####################################

##
@InstallMethod( ViewObj,
          [ IsQuiverRowsMorphism ],
  function( morphism )
    
    Print( "<A morphism in ", Name( CapCategory( morphism ) ),
            " defined by a ", NrRows( morphism ), " x ", NrCols( morphism ), " matrix of quiver algebra elements>"
            );
end );

##
@InstallMethod( ViewObj,
          [ IsQuiverRowsObject ],
  function( object )
    Print( "<An object in ", Name( CapCategory( object ) ),
            " defined by ", NrSummands( object ), " quiver vertices>"
            );
end );

##
@InstallMethod( Display,
               [ IsQuiverRowsObject ],
               
  function( object )
    
    Display( ListOfQuiverVertices( object ) );
    
end );

##
@InstallMethod( Display,
               [ IsQuiverRowsMorphism ],
               
  function( morphism )
    
    Print( "Source: ");
    Display( Source( morphism ) );
    Print( "  |\n");
    Print( "  |\n");
    Print( "Matrix: ");
    Display( MorphismMatrix( morphism ) );
    Print( "  |\n");
    Print( "  v\n");
    Print( "Range; ");
    Display( Target( morphism ) );
    
end );


##
@InstallMethod( LaTeXOutput,
               [ IsQuiverRowsObject ],
               
  function( obj )
    local l, exp_func;
    
    l = ListOfQuiverVertices( obj );
    
    if (IsEmpty( l ))
        
        return "0";
        
    end;
    
    exp_func = function( i )
        if (i == 1)
            return "";
        else
            return @Concatenation( "\\oplus", StringGAP( i ) );
        end;
    end;
    
    l = List( l, pair -> @Concatenation( "V_[", LabelAsString( pair[1] ), "]^[", exp_func( pair[2] ), "]" ) );
    
    return JoinStringsWithSeparator( l, " \\oplus " );
    
end );

##
@InstallMethod( LaTeXOutput,
               [ IsQuiverRowsMorphism ],
               
  function( morphism )
    local matrix, source, range;
    
    matrix = MorphismMatrix( morphism );
    
    if (IsEmpty( matrix ))
        matrix = "0";
    else
        
        matrix = JoinStringsWithSeparator(
            List( matrix, row -> JoinStringsWithSeparator( List( row, el -> @Concatenation( "CAPINTMARKER", StringGAP( el ) ) ), "\&" ) ),
            """\\"""
        );
        
        matrix = ReplacedString( matrix, "[ 1*", "[" );
        
        matrix = ReplacedString( matrix, "[ -1*", "[-" );
        
        matrix = ReplacedString( matrix, " + 1*", " + " );
        
        matrix = ReplacedString( matrix, " - 1*", " - " );
        
        matrix = ReplacedString( matrix, "CAPINTMARKER1*", "" );
        
        matrix = ReplacedString( matrix, "CAPINTMARKER-1*", "-" );
        
        matrix = ReplacedString( matrix, "CAPINTMARKER", "" );
        
        matrix = ReplacedString( matrix, "*", "" );
        
        matrix =  @Concatenation( "\\begin[pmatrix]", matrix, "\\end[pmatrix]" );
    
    end;
    
    if (ValueOption( "OnlyDatum" ) == true)
        
        return matrix;
        
    end;
    
    source = LaTeXOutput( Source( morphism ) );
    
    range = LaTeXOutput( Target( morphism ) );
    
    return @Concatenation( source, "\\xrightarrow[", matrix, "]", range );
    
end );


####################################
##
## Convenience
##
####################################

##
@InstallMethod( \.,
        [ IsQuiverRowsCategory, IsPosInt ],
  function( QRows, string_as_int )
    local name, A, q, a;

    name = NameRNam( string_as_int );

    A = UnderlyingQuiverAlgebra( QRows );

    q = QuiverOfAlgebra( A );

    a  = q[name];

    if (IsQuiverVertex( a ))

      return AsQuiverRowsObject( a, QRows );

    elseif (IsArrow( a ))

      return AsQuiverRowsMorphism( A[name], QRows );

    else

      Error( "the given component ", name, " is neither a vertex nor an arrow of the quiver q == ", q, "\n" );

    end;

end );

##
@InstallMethod( /,
               [ IsQuiverVertex, IsQuiverRowsCategory ],
               AsQuiverRowsObject
);

##
@InstallMethod( /,
               [ IsQuiverAlgebraElement, IsQuiverRowsCategory ],
               AsQuiverRowsMorphism );

##
@InstallMethod( /,
               [ IsPath, IsQuiverRowsCategory ],
               (p, QRows) -> PathAsAlgebraElement( UnderlyingQuiverAlgebra( QRows ), p )/QRows
);

##
@InstallMethod( *,
               [ IsQuiverRowsMorphism, IsQuiverRowsMorphism ],
               PreCompose
);

####################################
##
## Down
##
####################################

##
@InstallMethod( Down,
               [ IsQuiverRowsObject ],
               ListOfQuiverVertices );

##
@InstallMethod( DownOnlyMorphismData,
               [ IsQuiverRowsMorphism ],
               MorphismMatrix );
