# SPDX-License-Identifier: GPL-2.0-or-later
# Algebroids: Algebroids and bialgebroids as preadditive categories generated by enhanced quivers
#
# Reading the declaration part of the package.
#

include( "gap/LinearClosuresOfPathCategoriesAndTheirQuotients.gd.autogen.jl");

#= comment for Julia
#include( "gap/FpCategories.gd.autogen.jl");
#include( "gap/QuiverRows.gd.autogen.jl" );
#
#include( "gap/Algebroids.gd.autogen.jl");
#include( "gap/Functors.gd.autogen.jl");
#include( "gap/CategoryFromDataTables.gd.autogen.jl");
#include( "gap/CategoryOfFpAlgebras.gd.autogen.jl" );
#include( "gap/CategoryOfFpMatrixAlgebras.gd.autogen.jl" );
#include( "gap/AlgebroidFromDataTables.gd.autogen.jl");
#include( "gap/CategoryOfAlgebroids.gd.autogen.jl");
#include( "gap/Bialgebroids.gd.autogen.jl");
#include( "gap/Tools.gd.autogen.jl");
#
#if IsPackageMarkedForLoading( "JuliaInterface", ">= 0.2" ) then
#    include( "gap/Julia.gd.autogen.jl" );
#fi;
# =#
