# SPDX-License-Identifier: GPL-2.0-or-later
# Algebroids: Algebroids and bialgebroids as preadditive categories generated by enhanced quivers
#
# Reading the implementation part of the package.
#

include( "gap/LinearClosuresOfPathCategoriesAndTheirQuotients.gi.autogen.jl" );
include( "gap/GroebnerBasesForLinearClosuresOfPathCategories.gi.autogen.jl" );
include( "gap/QuotientsOfLinearClosuresOfPathCategories.gi.autogen.jl" );

#= comment for Julia
#include( "gap/FpCategories.gi.autogen.jl");
#include( "gap/QuiverRows.gi.autogen.jl" );
#
#include( "gap/precompiled_categories/CategoryFromDataTablesPrecompiled.gi.autogen.jl" );
#
#include( "gap/precompiled_categories/AdditiveClosureOfAlgebroidOfFiniteDimensionalQuiverAlgebraOfRightQuiverOverFieldPrecompiled.gi.autogen.jl" );
#include( "gap/precompiled_categories/AdditiveClosureOfAlgebroidOfFiniteDimensionalQuiverAlgebraOfRightQuiverOverZPrecompiled.gi.autogen.jl" );
#include( "gap/precompiled_categories/AdditiveClosureOfAlgebroidFromDataTablesPrecompiled.gi.autogen.jl" );
#
#include( "gap/precompiled_categories/AdelmanCategoryOfAdditiveClosureOfAlgebroidOfFiniteDimensionalQuiverAlgebraOfRightQuiverOverFieldPrecompiled.gi.autogen.jl" );
#include( "gap/precompiled_categories/AdelmanCategoryOfAdditiveClosureOfAlgebroidOfFiniteDimensionalQuiverAlgebraOfRightQuiverOverZPrecompiled.gi.autogen.jl" );
#
#include( "gap/Algebroids.gi.autogen.jl");
#include( "gap/QPA2.gi.autogen.jl");
#include( "gap/Functors.gi.autogen.jl");
#include( "gap/CategoryFromDataTables.gi.autogen.jl");
#include( "gap/CategoryOfFpAlgebras.gi.autogen.jl" );
#include( "gap/CategoryOfFpMatrixAlgebras.gi.autogen.jl" );
#include( "gap/AlgebroidFromDataTables.gi.autogen.jl");
#include( "gap/CategoryOfAlgebroids.gi.autogen.jl");
#include( "gap/Bialgebroids.gi.autogen.jl");
#include( "gap/Tools.gi.autogen.jl");
#include( "gap/QuotientsOfAlgebroidsFromDataTables.gi.autogen.jl" );
#
#if IsPackageMarkedForLoading( "JuliaInterface", ">= 0.2" ) then
#    include( "gap/Julia.gi.autogen.jl" );
#fi;
# =#
