# To avoid name clashes, we exclude some names from the global namespace of the extension module.
empty!(ExcludedNames)

append!(ExcludedNames, [
  :AmbientCategory,
  :AmbientCategory_OPERATION,
  :Cardinality,
  :Cardinality_OPERATION,
  :HasAmbientCategory,
  :HasCardinality,
  :SetAmbientCategory,
  :SetCardinality,
  :TheJuliaAttributeTypeAmbientCategory,
  :TheJuliaAttributeTypeCardinality,
  :HasUnderlyingCategory,
  :SetUnderlyingCategory,
  :UnderlyingCategory,
  :UnderlyingCategory_OPERATION,
  :TheJuliaAttributeTypeUnderlyingCategory,
  :HasPseudoInverse,
  :SetPseudoInverse,
  :PseudoInverse,
  :PseudoInverse_OPERATION,
  :TheJuliaAttributeTypePseudoInverse,
  :HasSize,
  :SetSize,
  :Size,
  :Size_OPERATION,
  :TheJuliaAttributeTypeSize,
  :HasUnderlyingMorphism,
  :SetUnderlyingMorphism,
  :UnderlyingMorphism,
  :UnderlyingMorphism_OPERATION,
  :TheJuliaAttributeTypeUnderlyingMorphism,
])
