name = "QuotientCategories"
uuid = "c103c924-3523-4680-a691-c88f3312ec70"
authors = [
	"Kamal Saleh <kamal.saleh@uni-siegen.de>"
]

# Transpiled from GAP's QuotientCategories v2025.06-01
version = "0.0.1"

[deps]
CAP = "d64df2ee-d2bb-46f4-8cbc-f03bb858f8cb"
ToolsForCategoricalTowers = "e2cf920d-0824-4cbb-97bb-0be40824f89f"
MatricesForHomalg = "29b9b1b6-efa6-450e-8188-a5a2c25df071"

[weakdeps]

[extensions]

[compat]
julia = "1.11"
CAP = "0.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
AdditiveClosuresForCAP = "bbee75d5-3cb4-4478-8ae7-eddc7864e69e"
FreydCategoriesForCAP = "cec356e3-7627-4f73-8308-af32cbf46c2b"

[targets]
test = ["Test", "Documenter", "AdditiveClosuresForCAP", "FreydCategoriesForCAP"]
