#!/bin/bash

# This script is autogenerated by Ansible to run the Julia package generation playbook.
ansible-playbook -i ~/.gap/pkg/PackageJanitor/gap_to_julia/hosts ~/.gap/pkg/PackageJanitor/gap_to_julia/site.yml -l ToolsForCategoricalTowers --diff "$@"
